const curriculumV2=[
{part:"1",id:"people",title:"Australia and its people",domains:[
["first-peoples","Aboriginal and Torres Strait Islander peoples"],["settlement","Early European settlement and development"],["states","States, territories and capital cities"],["traditions","Traditions and important days"],["flags","Australian National, Aboriginal and Torres Strait Islander flags"],["symbols","National symbols, colours, anthem and floral emblem"]]},
{part:"2",id:"rights",title:"Democratic beliefs, rights and liberties",domains:[
["democracy","Parliamentary democracy"],["rule-law","Rule of law"],["peaceful-change","Living peacefully and democratic change"],["speech","Freedom of speech and expression"],["association","Freedom of association"],["religion","Freedom of religion and secular government"],["equality-law","Equality under the law"],["gender","Gender equality"],["fair-go","Equality of opportunity and a fair go"],["responsibilities","Responsibilities of citizenship"],["privileges","Privileges of citizenship"],["participation","Participation in Australian society and taxation"]]},
{part:"3",id:"government",title:"Government and the law in Australia",domains:[
["say","How citizens have a say, voting and secret ballot"],["aec","Australian Electoral Commission"],["federation","Federation and the Constitution"],["referendum","Referendums and constitutional change"],["powers","Legislative, executive and judicial powers"],["head-state","Head of State and Governor-General"],["parliament","House of Representatives and Senate"],["leaders","Prime Minister, Premiers, Chief Ministers and mayors"],["levels","Responsibilities of the three levels of government"],["parties","Political parties, independents, government and Opposition"],["ministers","Ministers and Cabinet"],["laws","Bills, Parliament and Royal Assent"],["courts","Courts, judges, magistrates and juries"],["police","Police and Australian Federal Police"],["law-types","Criminal law, family violence and traffic law"]]},
{part:"4",id:"values",title:"Australian Values",domains:[
["freedom-dignity","Freedom and dignity of the individual"],["values-law","Rule of law and parliamentary democracy"],["values-freedoms","Speech, religion and association"],["values-equality","Equality under law and equality of opportunity"],["mutual-respect","Fair go, mutual respect and tolerance"],["community","Contribution, compassion, mateship and community"],["english","English as the national language"],["safety","Community safety, violence and cyber abuse"],["loyalty","Loyalty to Australia and citizenship obligations"]]}
];
const domainKnowledge={
"first-peoples":{part:"people",title:"First Peoples",teach:"Aboriginal and Torres Strait Islander peoples are Australia’s First Peoples. Their diverse cultures, languages and connections to Country continue today.",cue:"First Peoples → continuing cultures and connection to Country"},
"settlement":{part:"people",title:"Settlement and development",teach:"The First Fleet arrived from Great Britain in 1788. This marks British settlement and must not be confused with Federation in 1901.",cue:"1788 settlement ≠ 1901 Federation"},
"states":{part:"people",title:"States, territories and capitals",teach:"Australia has six states and two mainland territories. Canberra is the national capital.",cue:"Know every jurisdiction ↔ capital pair"},
"traditions":{part:"people",title:"Traditions and important days",teach:"Australia Day is 26 January and Anzac Day is 25 April. Ceremonies such as Welcome to Country and Acknowledgement of Country recognise First Peoples and connection to Country.",cue:"26 Jan Australia Day · 25 Apr Anzac Day"},
"flags":{part:"people",title:"Australia’s flags",teach:"The Australian National Flag, Australian Aboriginal Flag and Torres Strait Islander Flag are important recognised flags with distinct symbolism.",cue:"Know all three flags, not only the national flag"},
"symbols":{part:"people",title:"National symbols",teach:"Green and gold are the national colours, golden wattle is the national floral emblem, and Advance Australia Fair is the national anthem.",cue:"green + gold · golden wattle · Advance Australia Fair"},
"democracy":{part:"rights",title:"Parliamentary democracy",teach:"Australian citizens elect representatives to Parliament and can participate peacefully in public life.",cue:"citizens → elect representatives"},
"rule-law":{part:"rights",title:"Rule of law",teach:"Everyone is subject to Australian law. No person, organisation, official, cultural practice or religious rule is above it.",cue:"No one above Australian law"},
"peaceful-change":{part:"rights",title:"Peaceful democratic change",teach:"Political and social change should be pursued through peaceful, lawful democratic methods rather than violence.",cue:"disagree → participate peacefully"},
"speech":{part:"rights",title:"Freedom of speech",teach:"People may express ideas and opinions within Australian law while respecting the rights of others.",cue:"freedom operates within law"},
"association":{part:"rights",title:"Freedom of association",teach:"People may choose to join or leave lawful organisations and groups.",cue:"join or leave lawful groups"},
"religion":{part:"rights",title:"Freedom of religion",teach:"People may follow a religion or no religion. Australia has no official national religion and religious rules do not override Australian law.",cue:"belief is free · Australian law remains supreme"},
"equality-law":{part:"rights",title:"Equality under law",teach:"People are entitled to equal treatment under Australian law regardless of background.",cue:"same legal protection"},
"gender":{part:"rights",title:"Gender equality",teach:"Men and women have equal rights in Australia.",cue:"equal rights regardless of gender"},
"fair-go":{part:"rights",title:"Fair go",teach:"A fair go is associated with equality of opportunity, fairness and mutual respect.",cue:"fair opportunity, not guaranteed equal outcomes"},
"responsibilities":{part:"rights",title:"Responsibilities of citizenship",teach:"Responsibilities include obeying Australian laws, voting when required, serving on a jury when called and eligible, and defending Australia should the need arise.",cue:"law · vote · jury · defend"},
"privileges":{part:"rights",title:"Privileges of citizenship",teach:"Privileges include applying for an Australian passport, seeking election when eligible, certain public service or defence employment and consular assistance overseas.",cue:"passport · stand for office · consular help"},
"participation":{part:"rights",title:"Participation and taxation",teach:"Citizens are encouraged to participate in community life. Taxation helps fund government services and infrastructure.",cue:"participate + contribute"},
"say":{part:"government",title:"Voting and secret ballot",teach:"Eligible citizens enrol and vote. Voting is by secret ballot so an individual’s choice is private.",cue:"vote is compulsory when required; choice is secret"},
"aec":{part:"government",title:"Australian Electoral Commission",teach:"The Australian Electoral Commission administers federal elections and referendums and maintains the electoral roll.",cue:"AEC → elections · referendums · electoral roll"},
"federation":{part:"government",title:"Federation and Constitution",teach:"On 1 January 1901 the six colonies federated as the Commonwealth of Australia. The Constitution provides the framework for national government.",cue:"1901 → Commonwealth + Constitution"},
"referendum":{part:"government",title:"Referendums",teach:"The Australian Constitution can be changed through a referendum. Constitutional change requires the prescribed majority support, commonly described as a double majority.",cue:"Constitutional change → referendum"},
"powers":{part:"government",title:"Three powers",teach:"Legislative power makes laws, executive power puts them into action, and judicial power interprets and applies them.",cue:"MAKE → DO → JUDGE"},
"head-state":{part:"government",title:"Head of State and Governor-General",teach:"Australia is a constitutional monarchy. The King is Australia’s Head of State and the Governor-General represents the King at the Commonwealth level.",cue:"King → Head of State · Governor-General → representative"},
"parliament":{part:"government",title:"Australian Parliament",teach:"The Australian Parliament includes the House of Representatives and the Senate.",cue:"House + Senate"},
"leaders":{part:"government",title:"Political leaders",teach:"The Prime Minister leads the Australian Government; Premiers lead state governments; Chief Ministers lead territory governments; mayors lead many local councils.",cue:"PM · Premier · Chief Minister · Mayor"},
"levels":{part:"government",title:"Three levels",teach:"Federal government handles national matters, states and territories major regional services, and local councils community-level services.",cue:"national · regional · local"},
"parties":{part:"government",title:"Parties and Opposition",teach:"Elected representatives may belong to political parties or be independents. The party or coalition with sufficient support forms government; other major parliamentary forces form the Opposition.",cue:"government vs Opposition"},
"ministers":{part:"government",title:"Ministers and Cabinet",teach:"Ministers are responsible for government portfolios. Senior ministers form Cabinet and make major government decisions.",cue:"portfolio → minister · senior ministers → Cabinet"},
"laws":{part:"government",title:"Making laws",teach:"A proposed law is a Bill. Parliament considers Bills and Royal Assent is part of the process by which a passed Bill becomes law.",cue:"Bill → Parliament → Royal Assent → law"},
"courts":{part:"government",title:"Courts and juries",teach:"Judges and magistrates decide legal cases. In some criminal trials, a jury of citizens decides whether the accused is guilty based on the evidence and law.",cue:"judge/magistrate + jury"},
"police":{part:"government",title:"Police and AFP",teach:"Police maintain peace and safety and enforce law. The Australian Federal Police handles federal policing responsibilities.",cue:"police enforce law · AFP federal role"},
"law-types":{part:"government",title:"Criminal, family violence and traffic law",teach:"Serious offences are governed by criminal law. Domestic and family violence is not accepted in Australia, and road users must obey traffic laws.",cue:"violence is unlawful · traffic laws apply"},
"freedom-dignity":{part:"values",title:"Freedom and dignity",teach:"Australian Values include respect for the freedom and dignity of every individual.",cue:"respect lawful freedom + dignity"},
"values-law":{part:"values",title:"Law and democracy",teach:"Australian Values include commitment to parliamentary democracy and the rule of law.",cue:"democracy + law"},
"values-freedoms":{part:"values",title:"Freedoms",teach:"Freedom of speech, religion and association are important values exercised within Australian law.",cue:"freedom within law"},
"values-equality":{part:"values",title:"Equality",teach:"Australian Values include equality under law and equality of opportunity, including equal rights for men and women.",cue:"equal law + equal opportunity"},
"mutual-respect":{part:"values",title:"Mutual respect and tolerance",teach:"People should respect lawful differences and treat others with tolerance and fairness.",cue:"fair go + mutual respect"},
"community":{part:"values",title:"Community contribution",teach:"Compassion, mateship, volunteering and contributing to the community are valued parts of Australian society.",cue:"help · contribute · volunteer"},
"english":{part:"values",title:"English language",teach:"English is Australia’s national language and is an important unifying element in Australian society.",cue:"English → national language"},
"safety":{part:"values",title:"Community safety and cyber abuse",teach:"Violence, threats and abuse are inconsistent with community safety. Cyber abuse can use technology to threaten, intimidate, harass or humiliate.",cue:"online harm still counts as abuse"},
"loyalty":{part:"values",title:"Loyalty and obligations",teach:"Australian citizens pledge loyalty to Australia and its people and share civic obligations. Dual citizens may also have obligations under another country’s laws.",cue:"citizenship → loyalty + continuing obligations"}
};
const testableGlossary=[["Constitution","Australia’s supreme law and framework for government."],["constitutional monarchy","A monarch is Head of State and powers are limited by the Constitution."],["coalition","Two or more political parties joining to form government or Opposition."],["commission","A group with an official responsibility."],["criminal trial","A court hearing deciding whether a person is guilty or not guilty."],["cyber abuse","Using technology to threaten, intimidate, harass or humiliate with intent to harm."],["democracy","Government by the people through elected representatives."],["Federation","Six colonies joining as the Commonwealth of Australia in 1901."],["jury","Citizens who hear evidence and decide facts in some court cases."],["referendum","A vote on a proposed change to the Australian Constitution."],["rule of law","Everyone is subject to Australian law."],["secret ballot","A voting system where each person’s vote is private."]];
const modules=[
{id:"learn",icon:"▤",title:"Learn",desc:"Study the key topics from Our Common Bond",cls:"blue"},
{id:"readings",icon:"☰",title:"Readings",desc:"Read in-depth explanatory learning material",cls:"purple"},
{id:"study",icon:"⌘",title:"Study Guide",desc:"Trace concept lineage, insights and exam cues",cls:"gold"},
{id:"visual",icon:"▥",title:"Infographics",desc:"Explore visual memory guides",cls:"cyan"},
{id:"map",icon:"◇",title:"Map Lab",desc:"Learn states, territories and capitals",cls:"teal"},
{id:"cards",icon:"▣",title:"Flashcards",desc:"Build recall with spaced repetition",cls:"purple"},
{id:"game",icon:"⚡",title:"Keyword Forge",desc:"Match key terms and build recall streaks",cls:"green"},
{id:"games",icon:"◈",title:"Games Lab",desc:"Sort, match and classify key citizenship concepts",cls:"cyan"},
{id:"practice",icon:"◎",title:"Reinforce",desc:"Targeted practice to strengthen knowledge",cls:"orange"},
{id:"mistakes",icon:"▧",title:"Mistakes",desc:"Review and master your weak areas",cls:"red"},
{id:"values",icon:"♟",title:"Values Lab",desc:"Practise Australian Values scenarios",cls:"green"},
{id:"mock",icon:"✓",title:"Mock Exam",desc:"Simulate the real test · 20 questions",cls:"gold"}
];
const topicInfo={
people:{name:"Australia & its people",icon:"🇦🇺",items:["Aboriginal and Torres Strait Islander peoples","States, territories and capitals","Australia Day: 26 January","Anzac Day: 25 April","Federation: 1 January 1901","Flags, anthem and national symbols"]},
rights:{name:"Democratic rights & liberties",icon:"🗳️",items:["Parliamentary democracy","Rule of law","Freedom of speech and expression","Freedom of religion and association","Equality of men and women","Responsibilities and privileges"]},
government:{name:"Government & the law",icon:"🏛️",items:["The Australian Constitution","Legislative, executive and judicial powers","Federal, state/territory and local government","House of Representatives and Senate","How a Bill becomes law","Courts, police and justice"]},
values:{name:"Australian Values",icon:"🤝",items:["Respect for freedom and dignity","Freedom within Australian law","Equality of opportunity","Peaceful democratic participation","A fair go and mutual respect","Community participation and loyalty"]}
};
const lessonDetail={people:[["First peoples","Aboriginal and Torres Strait Islander peoples are Australia’s First Peoples, with continuing cultures and traditions."],["Federation","On 1 January 1901 the six colonies federated to form the Commonwealth of Australia."],["National days","Australia Day is 26 January. Anzac Day is 25 April."],["Symbols","Know the national flags, golden wattle, green and gold, and Advance Australia Fair."]],rights:[["Democracy","Citizens elect representatives and can participate peacefully in public life."],["Rule of law","Everyone is subject to Australian law. No person, group or religious rule is above it."],["Freedoms","Speech, expression, religion and association operate within Australian law."],["Citizenship","Responsibilities include obeying laws, voting when required and jury service when called and eligible."]],government:[["Constitution","The Constitution sets the basic rules for Australia’s system of government."],["Three powers","Legislative makes laws, executive puts laws into action, judicial interprets and applies laws."],["Three levels","Federal handles national matters, states and territories regional services, councils local services."],["Making laws","A proposed law is a Bill. Parliament considers it and Royal Assent is part of becoming law."]],values:[["Freedom and dignity","Respect the freedom and dignity of others, including lawful differences."],["Equality","Men and women have equal rights and people should have equality of opportunity."],["Peaceful democracy","Disagreement is resolved through discussion, voting and peaceful lawful action."],["Law first","Australian law applies even when a cultural, family or religious practice says otherwise."]]};
const conceptNotes={
people:{why:"These facts help you understand the story, symbols and geography of the country you are joining.",example:"Federation is not the same as European settlement: 1788 marks the First Fleet; 1901 marks the Commonwealth.",hook:"PEOPLE → PLACES → DATES → SYMBOLS"},
rights:{why:"Australian democracy depends on people having freedoms while everyone remains subject to the same law.",example:"You may peacefully criticise government, but freedom of speech does not give permission to break Australian law.",hook:"FREEDOM + LAW + EQUALITY"},
government:{why:"The test checks whether you can distinguish who makes laws, who carries them out and which level delivers services.",example:"Parliament makes laws; courts interpret and apply them. Local councils commonly handle local parks and rubbish.",hook:"MAKE → DO → JUDGE"},
values:{why:"Values questions test how Australian principles apply to real situations, not just whether you recognise a definition.",example:"If a cultural or religious practice conflicts with Australian law, Australian law takes precedence.",hook:"LAWFUL → PEACEFUL → RESPECTFUL"}
};
const keywords=[
["Federation","The six colonies joining as the Commonwealth of Australia in 1901","people"],
["Canberra","Australia’s national capital","people"],
["Anzac Day","25 April","people"],
["Rule of law","No person or group is above Australian law","rights"],
["Freedom of association","The freedom to join or leave lawful groups","rights"],
["A fair go","Fair opportunity and mutual respect","rights"],
["Legislative","Power that makes laws","government"],
["Executive","Power that puts laws into action","government"],
["Judicial","Power that interprets and applies laws","government"],
["Bill","A proposed new law introduced into Parliament","government"],
["Equality","Equal rights and opportunity regardless of characteristics such as gender","values"],
["Peaceful democracy","Using voting, discussion and lawful peaceful action rather than violence","values"]
];
let gameState={score:0,streak:0,round:0,current:null};
const studyGuide={
people:{title:"Australia & its people",summary:"Build a chronological and symbolic map of Australia, then connect dates and places to meaning.",lineage:[["Deep roots","Aboriginal and Torres Strait Islander peoples are Australia’s First Peoples. Their continuing cultures and connections to Country pre-date British settlement by many thousands of years."],["British settlement","The First Fleet arrived in 1788. This is a settlement milestone, not the date Australia became a federation."],["Colonies to Commonwealth","Six self-governing colonies agreed to federate. On 1 January 1901 the Commonwealth of Australia was formed."],["National identity today","States, territories, capitals, flags, commemorative days and symbols provide the civic geography and shared reference points used throughout the test."]],insight:"The exam often rewards distinguishing nearby ideas: settlement is not Federation; Canberra is the national capital even though Sydney and Melbourne are larger cities.",cue:"When you see a date, ask: settlement, gold-era change, Federation, or commemoration?"},
rights:{title:"Democratic beliefs, rights & liberties",summary:"Understand the balance: people have freedoms, but those freedoms operate within a common legal framework.",lineage:[["Representative democracy","Australia’s parliamentary democracy gives citizens a say by electing representatives and participating in public life."],["Rule of law","Government authority and individual freedom both sit under law. No person or group is above Australian law."],["Freedoms","Speech, religion and association allow people to hold and express different lawful views and affiliations."],["Equality and participation","Equality of opportunity, mutual respect and the idea of a fair go support participation across a diverse society."]],insight:"Freedom and law are not opposites in the test material. The recurring pattern is freedom within law, plus respect for the equal rights of others.",cue:"For scenario questions, reject options that use force, discrimination or claim a personal rule overrides Australian law."},
government:{title:"Government & the law",summary:"Separate institutions by function. Most confusion disappears once you ask who makes, executes or interprets a rule.",lineage:[["Constitutional framework","The Australian Constitution establishes the Commonwealth system and provides the framework for national government."],["Legislative power","Parliament makes laws. A proposed new law is a Bill."],["Executive power","The executive puts laws into action through government and administration."],["Judicial power","Courts interpret and apply laws independently when deciding cases."],["Levels of government","Federal, state or territory, and local government divide public responsibilities by scale rather than by the three powers."]],insight:"The three powers and three levels are two different maps. Powers describe function. Levels describe which sphere of government handles an area.",cue:"MAKE → DO → JUDGE maps to Legislative → Executive → Judicial."},
values:{title:"Australian Values",summary:"Treat Values as a decision system, not a vocabulary list. Apply the principles to behaviour.",lineage:[["Freedom and dignity","People are entitled to lawful freedom and should respect the dignity of others."],["Equality","Men and women have equal rights, and equality of opportunity is a core expectation."],["Peaceful democracy","Change should be pursued through voting, discussion, lawful campaigning and peaceful protest rather than violence."],["Law and shared obligations","Australian law applies to everyone. Cultural, family or religious rules do not displace it."],["Community","Mutual respect, participation and responsibility help people with different backgrounds live together peacefully."]],insight:"Values questions are deliberately practical. The safest reasoning pattern is not to memorise slogans but to test whether an action is lawful, peaceful, respectful and equal.",cue:"VALUES FILTER → Lawful? Peaceful? Respectful? Equal?"}
};
const visualStories={
people:{title:"Australia timeline",icon:"🇦🇺",nodes:[["First Peoples","Australia’s First Peoples have continuing cultures and connections to Country."],["1788","The First Fleet arrived from Great Britain. This marks the beginning of British settlement, not Federation."],["1851","Gold discoveries contributed to major population and economic change."],["1901","Six colonies federated on 1 January to form the Commonwealth of Australia."]],check:["Which date marks Federation?",["1788","1851","1901"],2]},
rights:{title:"Freedom within law",icon:"🗳️",nodes:[["Democracy","People elect representatives and participate in public life."],["Rule of law","No person or group is above Australian law."],["Freedom","Speech, religion and association operate within Australian law."],["Equality","People should have equal rights and equality of opportunity."]],check:["Which principle means nobody is above Australian law?",["Freedom of association","Rule of law","Federation"],1]},
government:{title:"Government architecture",icon:"🏛️",nodes:[["Legislative","Makes laws. Think Parliament."],["Executive","Puts laws into action through government administration."],["Judicial","Interprets and applies laws through courts."],["Three levels","Federal handles national matters, states/territories major regional services, councils local services."]],check:["Which power interprets and applies laws?",["Executive","Judicial","Legislative"],1]},
values:{title:"Values decision filter",icon:"🤝",nodes:[["Lawful","Australian law applies to everyone."],["Peaceful","Political and social disagreement should not be pursued through violence."],["Respectful","Respect the freedom and dignity of others."],["Equal","Men and women have equal rights and people should have equality of opportunity."]],check:["Which response best fits Australian Values?",["Violence to force change","Peaceful lawful protest","Preventing others voting"],1]}
};
let visualState=null;
const readingMaterial={people:{title:"Australia and its people",paras:["Australia’s story begins long before European settlement. Aboriginal and Torres Strait Islander peoples are Australia’s First Peoples, with diverse continuing cultures, languages, traditions and connections to Country.","European settlement began with the First Fleet in 1788. Separate British colonies later developed, and on 1 January 1901 six colonies federated to form the Commonwealth of Australia. Settlement and Federation are therefore different historical events.","Australia has six states and two mainland territories. Canberra is the national capital. Important national references include Australia Day on 26 January, Anzac Day on 25 April, the golden wattle, and the national colours green and gold."]},rights:{title:"Democratic beliefs, rights and liberties",paras:["Australia is a parliamentary democracy. Citizens elect representatives, while people can participate through voting, discussion, lawful campaigning and peaceful protest.","The rule of law means everyone is subject to Australian law. No individual, organisation, official, cultural practice or religious rule is above the law.","Freedoms include speech and expression, religion and association, exercised within Australian law. Equality of opportunity and the idea of a fair go reinforce dignity, respect and fair opportunity."]},government:{title:"Government and the law",paras:["The Australian Constitution establishes the basic framework for the Commonwealth system of government. Keep the three powers separate from the three levels of government.","Legislative power makes laws, executive power puts laws into action, and judicial power interprets and applies laws. A proposed new law introduced into Parliament is called a Bill.","The Australian Government deals with national matters such as defence, immigration and currency. States and territories manage services such as public hospitals and police. Local councils deal with services such as parks and rubbish collection."]},values:{title:"Australian Values",paras:["Values questions ask you to apply principles to situations. A useful filter is whether behaviour is lawful, peaceful, respectful and consistent with equality.","Respect for freedom and dignity includes accepting lawful differences. Equality means men and women have equal rights and people should have equality of opportunity. A fair go reflects fair opportunity and mutual respect.","Political disagreement should be pursued peacefully through voting, discussion, lawful campaigning and protest. Australian law remains the governing standard if a family, cultural or religious practice conflicts with it."]}};
const questionDomainMap={
"Australia became a federation in which year?":"federation",
"What is Australia’s national capital?":"states",
"Which colours are Australia’s national colours?":"symbols",
"Which is a responsibility of eligible Australian citizens aged 18 or over?":"responsibilities",
"What does rule of law mean?":"rule-law",
"Which statement describes freedom of religion?":"religion",
"Which are the three powers of government?":"powers",
"A proposed new law introduced into Parliament is called what?":"laws",
"Who interprets and applies the law in cases?":"courts",
"If a religious practice conflicts with Australian law, which takes precedence?":"values-law",
"Which best reflects equality in Australia?":"values-equality",
"A person strongly disagrees with a government decision. Which response reflects Australian values?":"peaceful-change",
"Which is consistent with peaceful democratic participation?":"values-law",
"A colleague is treated unfairly because of gender. Which principle applies?":"gender",
"What is Australia’s national floral emblem?":"symbols",
"When is Anzac Day commemorated?":"traditions",
"Freedom of association means people may…":"association",
"Which best describes a fair go?":"fair-go",
"Which two houses form the Australian Parliament?":"parliament",
"Which level commonly manages local parks and rubbish collection?":"levels",
"Two people hold different lawful religious beliefs. What best reflects Australian values?":"mutual-respect",
"Which response to political disagreement best reflects Australian values?":"peaceful-change"
};
const questions=[
["people","Australia became a federation in which year?",["1788","1851","1901","1915"],2,"Federation joined the six colonies into the Commonwealth on 1 January 1901."],
["people","What is Australia’s national capital?",["Sydney","Melbourne","Canberra","Adelaide"],2,"Canberra is the national capital."],
["people","Which colours are Australia’s national colours?",["Blue and white","Green and gold","Red and blue","Black and gold"],1,"Australia’s national colours are green and gold."],
["rights","Which is a responsibility of eligible Australian citizens aged 18 or over?",["Owning a home","Enrolling and voting","Joining a political party","Serving in the military"],1,"Eligible citizens aged 18 or over must enrol and vote."],
["rights","What does rule of law mean?",["Government is above the law","No person or group is above the law","Religious rules override law","Only citizens must obey law"],1,"Australian law applies to everyone."],
["rights","Which statement describes freedom of religion?",["Everyone must follow a religion","People may follow a religion or no religion","Only major religions are protected","Religious law replaces Australian law"],1,"People may practise a religion or choose no religion, within Australian law."],
["government","Which are the three powers of government?",["Federal, state, local","Legislative, executive, judicial","Parliament, police, council","King, Governor-General, Prime Minister"],1,"The three powers are legislative, executive and judicial."],
["government","A proposed new law introduced into Parliament is called what?",["A Bill","A ballot","A petition","A referendum"],0,"A proposed law is a Bill."],
["government","Who interprets and applies the law in cases?",["The media","The courts","Local councils","Political parties"],1,"Judicial power is exercised by courts."],
["values","If a religious practice conflicts with Australian law, which takes precedence?",["The religious rule","Family preference","Australian law","Whichever rule is older"],2,"Australian law applies to everyone."],
["values","Which best reflects equality in Australia?",["Leadership preference by gender","Equal opportunity regardless of gender","Only citizens receive legal protection","Ignore discrimination law"],1,"Equality includes equal opportunity regardless of gender."],
["values","A person strongly disagrees with a government decision. Which response reflects Australian values?",["Use violence","Peacefully protest within the law","Threaten officials","Stop others expressing views"],1,"Peaceful lawful protest is consistent with democratic values."],
["values","Which is consistent with peaceful democratic participation?",["Threatening opponents","Voting and lawful peaceful protest","Destroying property","Preventing others voting"],1,"Voting and peaceful lawful participation are democratic methods."],
["values","A colleague is treated unfairly because of gender. Which principle applies?",["Equality of opportunity","Compulsory association","Religious authority","Violence"],0,"Equality of opportunity applies regardless of gender."]
];
const sortGames={
citizenship:{title:"Responsibility or privilege?",bins:["Responsibility","Privilege"],items:[["Obey Australian laws","Responsibility"],["Vote in elections when required","Responsibility"],["Serve on a jury when called and eligible","Responsibility"],["Apply for an Australian passport","Privilege"],["Seek election to Parliament when eligible","Privilege"],["Receive Australian consular assistance overseas","Privilege"]]},
levels:{title:"Which level of government?",bins:["Federal","State / territory","Local"],items:[["Immigration","Federal"],["Defence","Federal"],["Currency","Federal"],["Public hospitals","State / territory"],["Police","State / territory"],["Public transport","State / territory"],["Rubbish collection","Local"],["Local parks","Local"],["Pet control","Local"]]},
powers:{title:"Which power?",bins:["Legislative","Executive","Judicial"],items:[["Makes laws","Legislative"],["Puts laws into action","Executive"],["Interprets and applies laws","Judicial"],["Parliament passing legislation","Legislative"],["Government administration","Executive"],["Courts deciding cases","Judicial"]]},
valuesort:{title:"Values scenario: lawful or not?",bins:["Consistent with values","Not consistent"],items:[["Peacefully protest a government decision","Consistent with values"],["Use violence to force political change","Not consistent"],["Respect another person’s lawful religion","Consistent with values"],["Treat a qualified applicant unfairly because of gender","Not consistent"],["Follow Australian law when a religious rule conflicts","Consistent with values"],["Prevent another citizen from voting","Not consistent"]]}
};
let sortState=null;let quest=null;
const MORE_QUESTIONS=[["people","What is Australia’s national floral emblem?",["Golden wattle","Waratah","Banksia","Flannel flower"],0,"Golden wattle is Australia’s national floral emblem."],["people","When is Anzac Day commemorated?",["1 January","25 April","26 January","11 November"],1,"Anzac Day is 25 April."],["rights","Freedom of association means people may…",["Join or leave lawful groups","Ignore Australian law","Force others to join groups","Avoid voting laws"],0,"People may freely join or leave lawful organisations."],["rights","Which best describes a fair go?",["Fair opportunity and mutual respect","Guaranteed identical outcomes","Ignoring unpopular laws","Preference based on gender"],0,"A fair go is linked to fair opportunity and mutual respect."],["government","Which two houses form the Australian Parliament?",["Senate and House of Representatives","Cabinet and Senate","High Court and Senate","Councils and Senate"],0,"Parliament consists of the Senate and House of Representatives."],["government","Which level commonly manages local parks and rubbish collection?",["Federal","Local council","High Court","Governor-General"],1,"Local councils commonly manage local parks and rubbish collection."],["values","Two people hold different lawful religious beliefs. What best reflects Australian values?",["Respect each person’s freedom","Force one to change","Ban both beliefs","Let religion override Australian law"],0,"Mutual respect includes respecting lawful differences in belief."],["values","Which response to political disagreement best reflects Australian values?",["Peaceful lawful campaigning","Threatening opponents","Destroying property","Stopping others voting"],0,"Political disagreement should be pursued peacefully and lawfully."]];questions.push(...MORE_QUESTIONS);
const domainQuestionBank=[
["first-peoples","people","Who are Australia’s First Peoples?",["Aboriginal and Torres Strait Islander peoples","People born after Federation","Only people living in the Northern Territory","The First Fleet"],0,"Aboriginal and Torres Strait Islander peoples are Australia’s First Peoples."],
["settlement","people","Which event occurred in 1788?",["Federation","Arrival of the First Fleet","Opening of Parliament House","The first referendum"],1,"The First Fleet arrived from Great Britain in 1788."],
["states","people","What is the capital of Western Australia?",["Darwin","Adelaide","Perth","Brisbane"],2,"Perth is the capital of Western Australia."],
["traditions","people","When is Australia’s Anzac Day?",["25 April","26 January","1 January","11 November"],0,"Anzac Day is commemorated on 25 April."],
["flags","people","Which set lists three important recognised Australian flags?",["National, Aboriginal and Torres Strait Islander flags","National, state and council flags only","Union Jack, EU and UN flags","Army, Navy and Air Force flags"],0,"The Australian National, Aboriginal and Torres Strait Islander flags are important recognised flags."],
["symbols","people","What is Australia’s national floral emblem?",["Waratah","Golden wattle","Banksia","Eucalyptus"],1,"The golden wattle is Australia’s national floral emblem."],
["democracy","rights","In a parliamentary democracy, citizens primarily choose representatives by…",["inheritance","voting","appointment by courts","military selection"],1,"Citizens elect representatives by voting."],
["rule-law","rights","Who is subject to Australian law?",["Only citizens","Only politicians","Everyone in Australia","Only adults"],2,"Everyone is subject to Australian law."],
["peaceful-change","rights","Which is an appropriate way to seek political change?",["Violence","Peaceful lawful participation","Threatening voters","Destroying property"],1,"Australian democracy expects change to be pursued peacefully and lawfully."],
["speech","rights","Freedom of speech in Australia means people may…",["express lawful opinions","ignore all laws","threaten anyone without consequence","prevent others speaking"],0,"Freedom of speech operates within Australian law."],
["association","rights","Freedom of association includes the right to…",["join or leave lawful groups","force others to join a group","ignore court orders","avoid all civic duties"],0,"People may join or leave lawful groups."],
["religion","rights","Which statement is correct about religion in Australia?",["Everyone must follow one religion","People may follow a religion or no religion within the law","Religious rules override Australian law","Only citizens may practise religion"],1,"Freedom of religion includes following a religion or no religion within Australian law."],
["equality-law","rights","Equality under the law means…",["laws apply differently by wealth","people have equal legal rights and protection","only citizens receive protection","government officials are above the law"],1,"People are entitled to equal treatment under Australian law."],
["gender","rights","Which statement reflects gender equality?",["Men and women have equal rights","Only men may lead organisations","Women have fewer legal rights","Rights depend on gender"],0,"Men and women have equal rights in Australia."],
["fair-go","rights","A fair go is most closely associated with…",["fair opportunity","guaranteed identical outcomes","ignoring laws","special rights based on gender"],0,"A fair go is associated with fair opportunity and mutual respect."],
["responsibilities","rights","Which is a citizenship responsibility?",["Obey Australian laws","Receive a passport automatically","Ignore jury summons","Avoid voting"],0,"Citizens must obey Australian laws."],
["privileges","rights","Which is a privilege of Australian citizenship?",["Applying for an Australian passport","Ignoring Australian law","Avoiding tax","Refusing all jury service"],0,"Australian citizens may apply for an Australian passport."],
["participation","rights","Why do Australians pay tax?",["To fund government services and infrastructure","To replace elections","To avoid obeying laws","Only to fund local parks"],0,"Taxation helps fund public services and infrastructure."],
["say","government","What does a secret ballot protect?",["The privacy of a person’s vote","The identity of candidates","The date of an election","The Constitution from change"],0,"A secret ballot keeps an individual’s vote private."],
["aec","government","What is a key role of the Australian Electoral Commission?",["Administer federal elections and maintain the electoral roll","Run the High Court","Command the Defence Force","Manage local rubbish"],0,"The AEC administers federal elections and referendums and maintains the electoral roll."],
["federation","government","What happened on 1 January 1901?",["Six colonies federated as the Commonwealth of Australia","The First Fleet arrived","Australia became a republic","The Constitution was abolished"],0,"The six colonies federated in 1901."],
["referendum","government","How can the Australian Constitution be formally changed?",["By a referendum meeting constitutional requirements","By a mayor alone","By a court petition only","By a newspaper poll"],0,"Constitutional change requires a referendum."],
["powers","government","Which power interprets and applies laws?",["Legislative","Executive","Judicial","Electoral"],2,"Judicial power interprets and applies laws."],
["head-state","government","Who is Australia’s Head of State?",["The Prime Minister","The King","The Chief Justice","The Governor-General"],1,"The King is Australia’s Head of State; the Governor-General represents the King at Commonwealth level."],
["parliament","government","Which two houses are in the Australian Parliament?",["House of Representatives and Senate","Cabinet and Senate","High Court and House","Councils and Senate"],0,"The Parliament includes the House of Representatives and Senate."],
["leaders","government","Who leads an Australian state government?",["Premier","Mayor","Governor-General","Chief Minister"],0,"A Premier leads a state government."],
["levels","government","Which level commonly manages local rubbish collection?",["Federal","State or territory","Local council","High Court"],2,"Local councils commonly manage local rubbish collection."],
["parties","government","What is the Opposition?",["The major parliamentary group not forming government","All judges","The police service","Local councils"],0,"The Opposition is the major parliamentary force not forming government."],
["ministers","government","What is Cabinet?",["A group of senior government ministers","All Australian judges","Every local mayor","The electoral roll"],0,"Cabinet consists of senior ministers who make major government decisions."],
["laws","government","What is a proposed law called?",["Bill","Ballot","Verdict","Coalition"],0,"A proposed law is a Bill."],
["courts","government","What may a jury do in some criminal trials?",["Decide facts and whether the accused is guilty based on evidence and law","Write new legislation","Elect the Prime Minister","Administer elections"],0,"Juries decide facts in some criminal trials."],
["police","government","What is a role of police?",["Enforce law and help maintain community safety","Write the Constitution","Choose senators","Issue all passports"],0,"Police enforce law and help maintain peace and safety."],
["law-types","government","Which statement is correct?",["Domestic and family violence is against Australian law","Traffic laws are optional","Criminal law only applies to citizens","Violence is acceptable in family disputes"],0,"Domestic and family violence is not accepted and can be criminal."],
["freedom-dignity","values","Which action respects individual dignity?",["Respecting another person’s lawful choices","Humiliating them because of background","Using violence to silence them","Removing their legal rights"],0,"Respect for freedom and dignity is an Australian Value."],
["values-law","values","Which principle is an Australian Value?",["Rule of law","Government by violence","Religious law above Australian law","Unequal legal rights"],0,"Commitment to the rule of law is an Australian Value."],
["values-freedoms","values","Which freedom is consistent with Australian Values?",["Freedom to follow a religion or no religion within the law","Freedom to threaten others","Freedom to ignore court orders","Freedom to use violence"],0,"Freedom of religion operates within Australian law."],
["values-equality","values","Australian Values support…",["equality of opportunity","legal rights based on gender","unequal treatment by background","preventing women from leadership"],0,"Equality of opportunity is an Australian Value."],
["mutual-respect","values","Which behaviour shows mutual respect?",["Respecting lawful differences","Threatening people with different views","Discriminating by gender","Preventing peaceful participation"],0,"Mutual respect includes respecting lawful differences."],
["community","values","Which action reflects contribution to the community?",["Volunteering to help others","Intimidating neighbours","Preventing community participation","Ignoring all civic obligations"],0,"Volunteering and helping others reflect community contribution and mateship."],
["english","values","What is Australia’s national language?",["English","French","Latin","No language is identified"],0,"English is Australia’s national language."],
["safety","values","Which is an example of cyber abuse?",["Using technology to threaten or humiliate someone with intent to harm","Sending a lawful meeting reminder","Reading a public website","Voting online in a survey"],0,"Cyber abuse can involve threatening, intimidating, harassing or humiliating someone using technology."],
["loyalty","values","What do Australian citizens pledge at citizenship?",["Loyalty to Australia and its people","Loyalty to a political party","To ignore Australian law overseas","To give up all personal beliefs"],0,"Citizens pledge loyalty to Australia and its people."]
];
domainQuestionBank.forEach(q=>{if(!questions.some(x=>questionDomainMap[x[1]]===q[0])){questions.push([q[1],q[2],q[3],q[4],q[5]]);questionDomainMap[q[2]]=q[0]}});
const masteryVariants=[
["settlement","people","Which statement correctly separates 1788 from 1901?",["1788 was British settlement; 1901 was Federation","1788 was Federation; 1901 was the First Fleet","Both dates refer to Federation","Both dates refer to Anzac Day"],0,"1788 marks the First Fleet and British settlement; 1901 marks Federation."],
["federation","government","Federation refers to…",["six colonies joining to form the Commonwealth","the arrival of the First Fleet","the first local council","a change of national anthem"],0,"Federation joined the six colonies as the Commonwealth in 1901."],
["responsibilities","rights","An eligible citizen is called for jury service. What does this represent?",["A citizenship responsibility","A passport privilege","Freedom of religion","A local-government service"],0,"Jury service when called and eligible is a citizenship responsibility."],
["privileges","rights","Which option is a citizenship privilege rather than a responsibility?",["Applying for an Australian passport","Obeying Australian laws","Voting when required","Jury service when called"],0,"Applying for an Australian passport is a privilege."],
["referendum","government","Citizens are asked to vote on a proposed constitutional change. What is this vote called?",["Referendum","Secret ballot only","Cabinet meeting","Royal Assent"],0,"A referendum is used for proposed changes to the Constitution."],
["powers","government","Parliament passes a new law. Which power is being exercised?",["Legislative","Executive","Judicial","Local"],0,"Making laws is legislative power."],
["levels","government","Public hospitals are primarily associated with which level?",["State or territory","Local council only","Judicial","Governor-General"],0,"States and territories have major responsibility for public hospitals."],
["parliament","government","A proposal is debated in the House of Representatives and Senate. Which institution is involved?",["Australian Parliament","High Court","AEC","Local council"],0,"The House and Senate are the two houses of the Australian Parliament."],
["head-state","government","What is the relationship between the King and Governor-General?",["The King is Head of State and the Governor-General represents the King at Commonwealth level","The Governor-General is Head of State and the King is Prime Minister","Both are elected senators","They lead local councils"],0,"The King is Head of State; the Governor-General is the King’s representative at Commonwealth level."],
["laws","government","After Parliament passes a Bill, which step is associated with it becoming law?",["Royal Assent","A local election","A jury verdict","A secret ballot"],0,"Royal Assent is part of the process by which a passed Bill becomes law."],
["values-law","values","A family tradition conflicts with Australian law. Which should be followed?",["Australian law","The family tradition regardless of law","Whichever rule is older","Only local council rules"],0,"Australian law applies to everyone."],
["mutual-respect","values","A neighbour has a different lawful belief. Which response best reflects Australian Values?",["Respect the difference","Threaten the neighbour","Prevent their participation","Demand they abandon the belief"],0,"Mutual respect includes respecting lawful differences."],
["safety","values","Someone repeatedly uses messages to threaten and humiliate another person. What concept may apply?",["Cyber abuse","Federation","Freedom of association","Royal Assent"],0,"Technology used to threaten, intimidate, harass or humiliate can be cyber abuse."]
];
masteryVariants.forEach(q=>{questions.push([q[1],q[2],q[3],q[4],q[5]]);questionDomainMap[q[2]]=q[0]});
const flashcards=[
["When did Australia federate?","1 January 1901","people"],
["National capital?","Canberra","people"],
["Australia Day?","26 January","people"],
["Anzac Day?","25 April","people"],
["Three powers of government?","Legislative · Executive · Judicial","government"],
["Proposed law in Parliament?","A Bill","government"],
["Rule of law?","No person or group is above the law","rights"],
["Voting age for eligible citizens?","18 years and over","rights"],
["Can religion override Australian law?","No","values"],
["Values pass requirement?","All 5 values questions correct","values"],
["Overall pass requirement?","At least 15 out of 20","values"],
["Standard test time?","45 minutes","people"]
];
const places=[["South Australia","Adelaide"],["Victoria","Melbourne"],["Queensland","Brisbane"],["Western Australia","Perth"],["Tasmania","Hobart"],["New South Wales","Sydney"],["Northern Territory","Darwin"],["Australian Capital Territory","Canberra"]];
const app=document.querySelector("#app");
let state=loadState(),session=null,cardIndex=0,flipped=false,mockTimer=null,mockEnds=0;
function loadState(){try{const s=JSON.parse(localStorage.getItem("atest-state")||"{}");return {stats:s.stats||{},known:s.known||{},missed:s.missed||{},mocks:s.mocks||[],reviews:s.reviews||{},domains:s.domains||{},domainEvidence:s.domainEvidence||{}}}catch{return {stats:{},known:{},missed:{},mocks:[],reviews:{},domains:{},domainEvidence:{}}}}
function save(){localStorage.setItem("atest-state",JSON.stringify(state))}
function logo(sizeClass=""){return '<span class="'+sizeClass+' brand-logo"><img src="assets/a-test-logo.png" alt="A-Test official logo" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'block\'"><svg style="display:none" viewBox="0 0 100 100"><circle cx="50" cy="50" r="43" fill="none" stroke="currentColor" stroke-width="5"/><path d="M24 72h20V55c-9-4-14-12-14-22 0-16 12-27 28-27 18 0 31 13 31 31 0 9-4 18-11 24v11h-17V47" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M42 66V43M58 69V28M73 60V39" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><circle cx="42" cy="39" r="6" fill="currentColor"/><circle cx="58" cy="23" r="6" fill="currentColor"/><circle cx="73" cy="34" r="6" fill="currentColor"/><path d="M18 80h64" stroke="currentColor" stroke-width="6" stroke-linecap="round"/></svg></span>'}
function pct(id){const s=state.stats[id]||{c:0,t:0};return s.t?Math.round(s.c/s.t*100):0}
function nextAction(){if(Object.values(state.missed).some(n=>n>0))return {label:"Review unresolved mistakes",view:"mistakes"};if((state.stats.values||{}).t&&pct("values")<100)return {label:"Strengthen Australian Values",view:"values"};const seen=Object.keys(topicInfo).filter(id=>(state.stats[id]||{}).t);if(!seen.length)return {label:"Start your first lesson",view:"learn"};const weak=Object.keys(topicInfo).sort((a,b)=>pct(a)-pct(b))[0];if(pct(weak)<80)return {label:"Train "+topicInfo[weak].name,topic:weak};return {label:"Take a mock exam",view:"mock"}}
function coverage(){const studied=curriculumV2.map(p=>({id:p.id,total:p.domains.length,mastered:Math.round(p.domains.length*Math.min(1,pct(p.id)/100))}));const total=studied.reduce((a,x)=>a+x.total,0),done=studied.reduce((a,x)=>a+x.mastered,0);return {parts:studied,total,done,pct:Math.round(done/total*100)}}
function syllabus(){const all=curriculumV2.flatMap(p=>p.domains),seen=all.filter(d=>(state.domains[d[0]]||0)>0).length,understood=all.filter(d=>(state.domains[d[0]]||0)>=2).length,verified=all.filter(d=>(state.domains[d[0]]||0)>=3).length;app.innerHTML=pageHead("CURRICULUM","Complete testable syllabus","Every domain has a canonical teaching object. Open a domain to learn the exact concept.")+'<section class="card coverage-summary"><div class="eyebrow">DOMAIN COVERAGE</div><h2>'+verified+' verified · '+understood+' understood · '+seen+' encountered · '+all.length+' total</h2><div class="progress-bar"><i style="width:'+Math.round(verified/all.length*100)+'%"></i></div></section><div class="curriculum-grid">'+curriculumV2.map(p=>'<article class="card curriculum-part"><div class="eyebrow">PART '+p.part+'</div><h2>'+topicInfo[p.id].icon+' '+p.title+'</h2><div class="domain-list">'+p.domains.map(d=>'<button class="domain-row domain-button" data-domain="'+d[0]+'"><span class="'+((state.domains[d[0]]||0)>=3?"domain-ok":"domain-open")+'">'+((state.domains[d[0]]||0)>=3?"✓":(state.domains[d[0]]||0)===2?"◆":(state.domains[d[0]]||0)===1?"◐":"○")+'</span><span>'+d[1]+'</span></button>').join("")+'</div></article>').join("")+'</div>'}
function openDomain(id){const d=domainKnowledge[id];state.domains[id]=Math.max(1,state.domains[id]||0);save();app.innerHTML=pageHead("DOMAIN STUDY",d.title,"One canonical concept. Learn it, remember the cue, then practise its parent part.")+'<article class="card domain-study"><div class="eyebrow">'+topicInfo[d.part].icon+' '+topicInfo[d.part].name+'</div><p class="lead">'+d.teach+'</p><div class="visual">'+d.cue+'</div><div class="actions"><button class="primary" data-domain-master="'+id+'">Mark understood</button><button data-topic="'+d.part+'">Practise this part</button><button data-view="syllabus">Back to curriculum</button></div></article>'}
function glossary(){
  const cards=testableGlossary.map(function(x){return '<article class="card"><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>'}).join("");
  app.innerHTML=pageHead("TESTABLE GLOSSARY","Know the language of the test","Key terms drawn from the official testable glossary.")+'<div class="cards">'+cards+'</div><div class="actions"><button class="primary" data-view="game">Practise keywords</button><button data-view="syllabus">Back to curriculum</button></div>';
}
function dashboard(){
const ps={people:pct("people"),rights:pct("rights"),government:pct("government"),values:pct("values")};const rec=nextAction();
app.innerHTML='<section class="hero"><div class="hero-main">'+logo("hero-logo")+'<div><h1><span>A-</span>TEST</h1><div class="tagline">LEARN · PRACTISE · BELONG</div><div class="promise">YOUR PATH TO AUSTRALIAN CITIZENSHIP</div></div></div><div class="hero-art"><div class="bridge"></div><div class="hero-quote">A Stronger<br>Australia<br>Together</div><div class="hero-meta">PEOPLE · RESPECT · OPPORTUNITY</div></div></section>'+
'<div class="actions" style="justify-content:center;margin:14px 0 20px"><button class="btn primary" data-view="study">⌘ Open Study Guide</button><button class="btn" data-view="readings">☰ Read in-depth material</button><button class="btn" data-view="games">◈ Games Lab</button></div><section class="pillars"><div class="pillar"><i>▤</i><div><b>Learn</b><small>Build knowledge</small></div></div><div class="pillar"><i>◉</i><div><b>Visualise</b><small>See the bigger picture</small></div></div><div class="pillar"><i>✺</i><div><b>Practise</b><small>Reinforce and improve</small></div></div><div class="pillar"><i>♕</i><div><b>Belong</b><small>Confident. Prepared. Australian.</small></div></div></section>'+
'<section class="feature-grid">'+modules.map(m=>'<button class="feature '+m.cls+'" data-view="'+m.id+'"><span class="icon">'+m.icon+'</span><span><h3>'+m.title+'</h3><p>'+m.desc+'</p></span><span class="go">›</span></button>').join("")+'</section>'+
'<section class="dashboard-lower"><div class="panel"><div class="panel-title">YOUR PROGRESS</div><div class="progress-grid">'+progress("people",ps.people,"#329dff")+progress("rights",ps.rights,"#31d7dc")+progress("government",ps.government,"#ffa550")+progress("values",ps.values,"#28e178")+'</div></div><div class="panel quick"><div class="panel-title">QUICK ACTIONS</div><button data-view="learn">▶ <span>Continue learning</span><b>›</b></button><button id="next-best">⤨ <span>Best next action</span><b>›</b></button><button data-view="cards">▣ <span>Review flashcards</span><b>›</b></button><button data-view="mock">▥ <span>Take a mock exam</span><b>›</b></button></div><div class="panel quote"><div class="qmark">“</div><blockquote>Australia is strengthened by what we do: a fair go, a helping hand, and a better tomorrow together.</blockquote><small>A STRONGER AUSTRALIA TOGETHER</small></div></section>';
}
function progress(id,p,color){return '<div class="progress-item"><div class="ring" style="--p:'+p+';--ring:'+color+'"><strong>'+p+'%</strong></div><p>'+topicInfo[id].name+'</p></div>'}
function pageHead(kicker,title,lead){return '<div class="page-head"><div class="eyebrow">'+kicker+'</div><h2>'+title+'</h2><p class="lead">'+lead+'</p></div>'}
function study(){app.innerHTML=pageHead("STUDY GUIDE","Deep study with concept lineage","Trace each idea from its roots to its present civic meaning, then convert the insight into an exam cue.")+'<div class="study-index">'+Object.entries(studyGuide).map(([id,g])=>'<button class="card study-index-card" data-study="'+id+'"><span>'+topicInfo[id].icon+'</span><div><h3>'+g.title+'</h3><p>'+g.summary+'</p></div></button>').join("")+'</div>'}
function openStudy(id){const g=studyGuide[id];app.innerHTML=pageHead("STUDY GUIDE",topicInfo[id].icon+" "+g.title,g.summary)+'<section class="card study-insight"><div class="eyebrow">CORE INSIGHT</div><p>'+g.insight+'</p></section><div class="lineage">'+g.lineage.map((x,i)=>'<article class="lineage-step"><span>'+(i+1)+'</span><div><div class="eyebrow">LINEAGE '+(i+1)+'</div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></article>').join("")+'</div><section class="card study-cue"><div class="eyebrow">EXAM CUE</div><h3>'+g.cue+'</h3></section><div class="actions"><button class="primary" data-topic="'+id+'">Test this topic</button><button data-view="readings">Read long-form material</button><button data-view="study">Study another topic</button></div>'}
function readings(){app.innerHTML=pageHead("READINGS","In-depth learning material","Read for understanding, then retrieve what you learned.")+'<div class="cards">'+Object.entries(readingMaterial).map(([id,r])=>'<article class="card reading-card"><div class="eyebrow">'+topicInfo[id].icon+' '+id.toUpperCase()+'</div><h2>'+r.title+'</h2>'+r.paras.map(p=>'<p>'+p+'</p>').join("")+'<div class="actions"><button class="primary" data-topic="'+id+'">Check understanding</button><button data-lesson="'+id+'">Open lesson</button></div></article>').join("")+'</div>'}
function lesson(id){const t=topicInfo[id],n=conceptNotes[id];app.innerHTML=pageHead("DEEP LESSON",t.icon+" "+t.name,"Understand the idea, then retrieve it.")+'<div class="card" style="margin-bottom:18px"><h3>Why this matters</h3><p>'+n.why+'</p><h3>Example</h3><p>'+n.example+'</p><div class="visual">'+n.hook+'</div></div><div class="cards">'+lessonDetail[id].map(x=>'<article class="card"><h3>'+x[0]+'</h3><p>'+x[1]+'</p></article>').join("")+'</div><div class="actions"><button class="primary" data-topic="'+id+'">Check my recall</button><button data-view="learn">Back to Learning Hub</button></div>'}
function learn(){app.innerHTML=pageHead("LEARNING HUB","Learn the four testable areas","Build understanding first, then lock it in with visualisation and retrieval.")+'<div class="cards">'+Object.entries(topicInfo).map(([id,t])=>'<article class="card"><h3>'+t.icon+' '+t.name+'</h3><ul>'+t.items.map(x=>'<li>'+x+'</li>').join("")+'</ul><div class="actions"><button class="primary" data-lesson="'+id+'">Open lesson</button><button data-topic="'+id+'">Practise topic</button></div></article>').join("")+'</div>'}
function visual(){app.innerHTML=pageHead("VISUAL STORIES","Explore the ideas","Choose a story, tap through each concept, then complete its mini-check.")+'<div class="cards">'+Object.entries(visualStories).map(([id,v])=>'<button class="card visual-story-card" data-story="'+id+'"><div class="story-icon">'+v.icon+'</div><h3>'+v.title+'</h3><p>'+v.nodes.length+' interactive concepts + mini-check</p></button>').join("")+'</div>'}
function openStory(id){visualState={id,seen:[]};drawStory()}
function drawStory(){const v=visualStories[visualState.id];app.innerHTML=pageHead("VISUAL STORY",v.icon+" "+v.title,"Tap each node to reveal the meaning. Complete all nodes to unlock the mini-check.")+'<div class="story-track">'+v.nodes.map((n,i)=>'<button class="story-node '+(visualState.seen.includes(i)?"seen":"")+'" data-story-node="'+i+'"><span>'+(i+1)+'</span><b>'+n[0]+'</b></button>').join("")+'</div><div class="card story-detail" id="story-detail"><p class="hint">Choose a node to explore it.</p></div>'+(visualState.seen.length===v.nodes.length?'<div class="actions"><button class="primary" data-story-check>Unlock mini-check →</button></div>':"")}
function storyNode(i){if(!visualState.seen.includes(i))visualState.seen.push(i);const v=visualStories[visualState.id],n=v.nodes[i];drawStory();document.querySelector("#story-detail").innerHTML='<div class="eyebrow">CONCEPT '+(i+1)+'</div><h2>'+n[0]+'</h2><p class="lead">'+n[1]+'</p>'}
function storyCheck(){const v=visualStories[visualState.id],c=v.check;app.innerHTML=pageHead("MINI-CHECK",v.icon+" "+v.title,"Use retrieval, not recognition.")+'<section class="card quiz"><div class="question">'+c[0]+'</div><div class="choices">'+c[1].map((x,i)=>'<button class="choice" data-story-answer="'+i+'">'+x+'</button>').join("")+'</div><div id="story-feedback"></div></section>'}
function storyAnswer(i){const v=visualStories[visualState.id],c=v.check,ok=i===c[2],st=state.stats[visualState.id]||{c:0,t:0};st.t++;if(ok)st.c++;state.stats[visualState.id]=st;save();document.querySelectorAll("[data-story-answer]").forEach((b,n)=>{b.disabled=true;if(n===c[2])b.classList.add("correct");else if(n===i)b.classList.add("wrong")});document.querySelector("#story-feedback").innerHTML='<div class="feedback"><b class="'+(ok?"good":"bad")+'">'+(ok?"✓ Visual story mastered":"✕ Review the story once more")+'</b><p>'+v.nodes.find(n=>n[0].toLowerCase().includes(c[1][c[2]].toLowerCase().split(" ")[0]))?.[1]+'</p><div class="actions"><button class="primary" data-view="visual">Choose another story</button><button data-story="'+visualState.id+'">Replay story</button></div></div>'}
function map(){app.innerHTML=pageHead("MAP LAB","States, territories & capitals","Explore the pairs, then test yourself with a scored capital challenge.")+'<div class="actions"><button class="primary" data-mapquiz>▶ Capital Challenge</button></div>'+'<div class="maplab"><div class="card">'+places.map((p,i)=>'<button class="statebtn" data-place="'+i+'">'+p[0]+'</button>').join("")+'</div><div class="card" id="place"><h3>Choose a state or territory</h3><p class="hint">Say the capital aloud before revealing it.</p></div></div>'}
function mapQuiz(){const items=shuffle(places.slice());session={mapItems:items,i:0,score:0,mode:"mapquiz"};drawMapQuiz()}
function drawMapQuiz(){const p=session.mapItems[session.i],opts=shuffle([p[1],...shuffle(places.filter(x=>x[1]!==p[1])).slice(0,3).map(x=>x[1])]);app.innerHTML=pageHead("CAPITAL CHALLENGE","What is the capital of "+p[0]+"?","Question "+(session.i+1)+" / "+session.mapItems.length+" · Score "+session.score)+'<section class="card quiz"><div class="choices">'+opts.map(x=>'<button class="choice" data-mapanswer="'+encodeURIComponent(x)+'">'+x+'</button>').join("")+'</div></section>'}
function mapAnswer(ans){const p=session.mapItems[session.i],ok=ans===p[1];if(ok)session.score++;const st=state.stats.people||{c:0,t:0};st.t++;if(ok)st.c++;state.stats.people=st;save();session.i++;if(session.i>=session.mapItems.length){app.innerHTML=pageHead("MAP CHALLENGE COMPLETE",session.score+" / "+session.mapItems.length,"Capital recall now contributes to Australia & its people mastery.")+'<button class="btn primary" data-view="map">Play again</button>';return}drawMapQuiz()}
function showPlace(i){document.querySelectorAll(".statebtn").forEach((b,n)=>b.classList.toggle("active",n===i));const p=places[i];document.querySelector("#place").innerHTML='<h3>'+p[0]+'</h3><p class="hint">What is the capital?</p><button class="btn primary" data-reveal="'+i+'">Reveal</button>'}
function revealPlace(i){const p=places[i];document.querySelector("#place").innerHTML='<h3>'+p[0]+'</h3><div class="capital">'+p[1]+'</div><p>Lock the pair together: <b>'+p[0]+' → '+p[1]+'</b></p>'}
function cards(){const now=Date.now(),due=flashcards.map((c,i)=>({i,d:state.reviews[i]||0})).filter(x=>x.d<=now).sort((a,b)=>a.d-b.d);if(due.length&&!flipped)cardIndex=due[0].i;const c=flashcards[cardIndex],known=!!state.known[cardIndex];app.innerHTML=pageHead("FLASHCARDS","Build recall","Think first, reveal second, then rate your recall.")+'<section class="card flash"><div class="eyebrow">'+c[2].toUpperCase()+' · '+(cardIndex+1)+' / '+flashcards.length+'</div><div class="face">'+(flipped?c[1]:c[0])+'</div><p class="hint">'+(flipped?"Answer":"Retrieve it before you tap reveal.")+'</p><div class="actions" style="justify-content:center"><button class="primary" data-flip>'+(flipped?"Show question":"Reveal answer")+'</button>'+(flipped?'<button data-rate="0">× Review again</button><button data-rate="1">✓ I know it</button>':"")+'</div><p class="'+(known?"good":"hint")+'">'+(known?"✓ Marked known":"Not mastered yet")+'</p></section><div class="actions" style="justify-content:center"><button data-prev>← Previous</button><button data-next>Next →</button></div>'}
function adaptiveReinforce(){const misses=Object.keys(state.missed).filter(k=>state.missed[k]>0),weak=Object.keys(topicInfo).sort((a,b)=>pct(a)-pct(b))[0];let q=questions.filter(x=>misses.includes(x[1]));q=q.concat(questions.filter(x=>x[0]===weak&&!q.includes(x)));startSession(shuffle(q).slice(0,10),"adaptive")}
function practice(){app.innerHTML=pageHead("REINFORCE","Targeted practice","Choose a topic or train everything together.")+'<div class="cards">'+Object.entries(topicInfo).map(([id,t])=>'<button class="card" data-topic="'+id+'" style="text-align:left;cursor:pointer"><h3>'+t.icon+' '+t.name+'</h3><p>Focused retrieval drill</p></button>').join("")+'</div><div class="actions"><button class="primary" data-adaptive>Adaptive drill</button><button data-topic="all">Mixed drill</button><button data-view="mistakes">Review mistakes</button></div>'}
function mistakes(){const ks=Object.keys(state.missed).filter(k=>state.missed[k]>0).sort((a,b)=>state.missed[b]-state.missed[a]);if(!ks.length){app.innerHTML=pageHead("MISTAKES","Clean slate ✓","No unresolved mistakes yet. Keep practising to generate useful signals.")+'<button class="btn primary" data-view="practice">Start practice</button>';return}app.innerHTML=pageHead("MISTAKES","Turn errors into assets","The questions below are currently your highest-value review opportunities.")+'<div class="cards">'+ks.map(k=>'<article class="card"><div class="eyebrow">'+state.missed[k]+' MISS'+(state.missed[k]>1?"ES":"")+'</div><h3>'+k+'</h3></article>').join("")+'</div><div class="actions"><button class="primary" data-action="mistakes">Train my mistakes</button></div>'}
function readiness(){const ms=state.mocks.slice(-5),recent3=ms.slice(-3),consistent=recent3.length===3&&recent3.every(m=>m.score>=15&&m.values===5),valueStreak=[...state.mocks].reverse().findIndex(m=>m.values!==5),streak=valueStreak<0?state.mocks.length:valueStreak;const topics=Object.keys(topicInfo).map(id=>({id,p:pct(id)})),unresolved=Object.values(state.missed).filter(n=>n>0).length,mastery=Math.round(topics.reduce((a,x)=>a+x.p,0)/topics.length),ready=consistent&&mastery>=80&&pct("values")>=90&&unresolved===0;app.innerHTML=pageHead("EXAM READINESS","Your readiness cockpit","Passing once is useful. Consistent performance is the stronger signal.")+'<div class="cards"><article class="card"><div class="eyebrow">READINESS SIGNAL</div><h2 class="'+(consistent?"good":"bad")+'">'+(ready?"CONSISTENTLY READY":"BUILDING READINESS")+'</h2><p>'+(ready?"Mocks, topic mastery, Values and mistake recovery all meet the readiness standard.":"Readiness now combines mock consistency, 80%+ topic mastery, strong Values performance and zero unresolved mistakes.")+'</p></article><article class="card"><div class="eyebrow">VALUES STREAK</div><h2>'+streak+'</h2><p>consecutive mock'+(streak===1?"":"s")+' with 5/5 Values</p></article></div><div class="card" style="margin-top:18px"><h3>Topic heatmap</h3><div class="progress-grid">'+topics.map(x=>progress(x.id,x.p,x.p>=85?"#28e178":x.p>=75?"#f4c651":"#ff6767")).join("")+'</div></div><div class="card" style="margin-top:18px"><h3>Recent mock history</h3>'+(ms.length?ms.reverse().map((m,i)=>'<p><b class="'+(m.pass?"good":"bad")+'">'+m.score+'/20 · Values '+m.values+'/5</b> <span class="hint">Attempt '+(state.mocks.length-i)+'</span></p>').join(""):'<p class="hint">No mock exams completed yet.</p>')+'<div class="actions"><button class="primary" data-view="mock">Take a mock exam</button><button data-view="practice">Target weak areas</button></div></div>'}
function games(){const best=Number(localStorage.getItem("atest-quest-best")||0);app.innerHTML=pageHead("CITIZENSHIP QUEST","A real learning game","Clear four missions with three lives. Correct answers earn XP and streak multipliers.")+'<section class="card quest-hero"><div><div class="eyebrow">BEST SCORE</div><h2>'+best+' XP</h2><p>4 missions · 3 lives · streak bonuses</p></div><button class="btn primary" data-quest-start>▶ Start Quest</button></section><div class="cards">'+Object.entries(sortGames).map(([id,g],i)=>'<article class="card"><div class="eyebrow">MISSION '+(i+1)+'</div><h3>'+["🪪","🏛️","⚖️","🤝"][i]+' '+g.title+'</h3><p>'+g.items.length+' challenges</p></article>').join("")+'</div>'}
function startQuest(){quest={mission:0,index:0,lives:3,xp:0,streak:0,maxStreak:0};loadMission()}
function loadMission(){const ids=Object.keys(sortGames);if(quest.mission>=ids.length)return winQuest();quest.id=ids[quest.mission];quest.items=shuffle(sortGames[quest.id].items.slice());quest.index=0;drawQuest()}
function drawQuest(){const g=sortGames[quest.id],item=quest.items[quest.index],mult=Math.min(3,1+Math.floor(quest.streak/3));app.innerHTML='<section class="quest-shell"><div class="quest-hud"><div><small>MISSION</small><b>'+(quest.mission+1)+'/4</b></div><div><small>LIVES</small><b class="lives">'+("♥ ".repeat(quest.lives)||"0")+'</b></div><div><small>STREAK</small><b>🔥 '+quest.streak+'</b></div><div><small>MULTIPLIER</small><b>×'+mult+'</b></div><div><small>XP</small><b>'+quest.xp+'</b></div></div><div class="card quest-card"><div class="eyebrow">'+g.title.toUpperCase()+' · '+(quest.index+1)+'/'+quest.items.length+'</div><div class="question">'+item[0]+'</div><div class="choices">'+g.bins.map(x=>'<button class="choice" data-quest-bin="'+encodeURIComponent(x)+'">'+x+'</button>').join("")+'</div><div id="quest-feedback"></div></div></section>'}
function questAnswer(bin){const item=quest.items[quest.index],ok=bin===item[1],mult=Math.min(3,1+Math.floor(quest.streak/3));if(ok){quest.streak++;quest.maxStreak=Math.max(quest.maxStreak,quest.streak);quest.xp+=100*mult}else{quest.lives--;quest.streak=0}const questTopic={citizenship:"rights",levels:"government",powers:"government",valuesort:"values"}[quest.id];const qs=state.stats[questTopic]||{c:0,t:0};qs.t++;if(ok)qs.c++;state.stats[questTopic]=qs;save();document.querySelectorAll("[data-quest-bin]").forEach(x=>{x.disabled=true;const v=decodeURIComponent(x.dataset.questBin);if(v===item[1])x.classList.add("correct");else if(v===bin)x.classList.add("wrong")});document.querySelector("#quest-feedback").innerHTML='<div class="feedback"><b class="'+(ok?"good":"bad")+'">'+(ok?"+"+(100*mult)+" XP":"♥ Life lost")+'</b><p><strong>'+item[0]+'</strong> → '+item[1]+'</p><button class="btn primary" id="quest-next">'+(quest.lives?"Continue":"Results")+'</button></div>';document.querySelector("#quest-next").onclick=()=>{if(!quest.lives)return loseQuest();quest.index++;if(quest.index>=quest.items.length){quest.xp+=250;quest.mission++;return loadMission()}drawQuest()}}
function winQuest(){const best=Math.max(quest.xp,Number(localStorage.getItem("atest-quest-best")||0));localStorage.setItem("atest-quest-best",best);const rank=quest.xp>=5000?"Federation Master":quest.xp>=3500?"Civic Champion":"Citizen Scholar";app.innerHTML=pageHead("QUEST COMPLETE","🏆 "+rank,quest.xp+" XP · Best streak "+quest.maxStreak)+'<section class="card quest-result"><div class="quest-trophy">🏆</div><h2>All missions cleared</h2><div class="actions"><button class="primary" data-quest-start>Play again</button><button data-view="readiness">Readiness</button></div></section>'}
function loseQuest(){const best=Math.max(quest.xp,Number(localStorage.getItem("atest-quest-best")||0));localStorage.setItem("atest-quest-best",best);app.innerHTML=pageHead("QUEST OVER","Recharge and return",quest.xp+" XP · Best streak "+quest.maxStreak)+'<section class="card quest-result"><div class="quest-trophy">🛡️</div><h2>Three lives used</h2><p>Review the missed concepts and come back for the clear.</p><div class="actions"><button class="primary" data-quest-start>Retry quest</button><button data-view="learn">Review lessons</button></div></section>'}
function game(){gameState={score:0,streak:0,round:0,current:null};nextGame()}
function nextGame(){if(gameState.round>=10){app.innerHTML=pageHead("KEYWORD FORGE","Run complete ⚡","You scored "+gameState.score+" / 10.")+'<div class="card"><h3>Best streak: '+gameState.streak+'</h3><p>Run it again to make the language automatic.</p><div class="actions"><button class="primary" data-view="game">Play again</button><button data-view="learn">Review lessons</button></div></div>';return}const correct=keywords[Math.floor(Math.random()*keywords.length)],others=shuffle(keywords.filter(x=>x[0]!==correct[0])).slice(0,3),opts=shuffle([correct,...others]);gameState.current=correct;app.innerHTML=pageHead("KEYWORD FORGE","Match the keyword","Round "+(gameState.round+1)+" / 10 · Score "+gameState.score)+'<section class="card quiz"><div class="question">'+correct[1]+'</div><div class="choices">'+opts.map(x=>'<button class="choice" data-keyword="'+encodeURIComponent(x[0])+'">'+x[0]+'</button>').join("")+'</div><div id="game-feedback"></div></section>'}
function gameAnswer(term){const ok=term===gameState.current[0];if(ok){gameState.score++;gameState.streak++}else gameState.streak=0;gameState.round++;document.querySelectorAll("[data-keyword]").forEach(b=>{b.disabled=true;const t=decodeURIComponent(b.dataset.keyword);if(t===gameState.current[0])b.classList.add("correct");else if(t===term)b.classList.add("wrong")});document.querySelector("#game-feedback").innerHTML='<div class="feedback"><b class="'+(ok?"good":"bad")+'">'+(ok?"✓ Forged":"✕ Reforge")+'</b><p><strong>'+gameState.current[0]+'</strong> → '+gameState.current[1]+'</p><button class="btn primary" id="game-next">Next</button></div>';document.querySelector("#game-next").onclick=nextGame}
function values(){start("values")}
function mock(){if(mockTimer)clearInterval(mockTimer);const valuesQ=questions.filter(q=>q[0]==="values");const other=questions.filter(q=>q[0]!=="values");const picked=[];for(let i=0;i<15;i++)picked.push(other[i%other.length]);for(let i=0;i<5;i++)picked.push(valuesQ[i%valuesQ.length]);startSession(shuffle(picked),"mock");mockEnds=Date.now()+45*60*1000;startMockClock()}
function startMockClock(){if(mockTimer)clearInterval(mockTimer);mockTimer=setInterval(()=>{if(!session||session.mode!=="mock"){clearInterval(mockTimer);mockTimer=null;return}const left=Math.max(0,mockEnds-Date.now()),el=document.querySelector("#mock-clock");if(el)el.textContent=Math.floor(left/60000)+":"+String(Math.floor((left%60000)/1000)).padStart(2,"0");if(left<=0){clearInterval(mockTimer);mockTimer=null;finish()}},1000)}
function start(mode){let q=mode==="all"?questions.slice():questions.filter(x=>x[0]===mode);startSession(shuffle(q),mode)}
function startSession(q,mode){session={q,i:0,score:0,mode,valuesCorrect:0};drawQuestion()}
function drawQuestion(){const q=session.q[session.i];app.innerHTML='<section class="card quiz"><div class="eyebrow">'+(session.mode==="mock"?'MOCK EXAM · <span id="mock-clock">45:00</span>':"REINFORCEMENT")+' · '+(session.i+1)+' / '+session.q.length+'</div><div class="question">'+q[1]+'</div><div class="choices">'+q[2].map((x,i)=>'<button class="choice" data-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+x+'</button>').join("")+'</div><div id="feedback"></div></section>'}
function answer(i){const q=session.q[session.i],ok=i===q[3],domain=questionDomainMap[q[1]];if(ok){session.score++;if(q[0]==="values")session.valuesCorrect++;state.missed[q[1]]=0}else state.missed[q[1]]=(state.missed[q[1]]||0)+1;const s=state.stats[q[0]]||{c:0,t:0};s.t++;if(ok)s.c++;state.stats[q[0]]=s;if(domain){const ev=state.domainEvidence[domain]||{c:0,t:0};ev.t++;if(ok)ev.c++;state.domainEvidence[domain]=ev;const old=state.domains[domain]||0,acc=ev.c/ev.t;if(ev.t>=3&&ev.c>=2&&acc>=.75)state.domains[domain]=Math.max(old,3);else if(ev.t>=1)state.domains[domain]=Math.max(old,1)}save();document.querySelectorAll(".choice").forEach((b,n)=>{b.disabled=true;if(n===q[3])b.classList.add("correct");else if(n===i)b.classList.add("wrong")});document.querySelector("#feedback").innerHTML='<div class="feedback"><b class="'+(ok?"good":"bad")+'">'+(ok?"✓ Correct":"✕ Not yet")+'</b><p>'+q[4]+'</p><button class="btn primary" id="next">'+(session.i===session.q.length-1?"Finish":"Next")+'</button></div>';document.querySelector("#next").onclick=()=>{session.i++;session.i>=session.q.length?finish():drawQuestion()}}
function finish(){if(mockTimer){clearInterval(mockTimer);mockTimer=null}if(session.mode==="mock"){const pass=session.score>=15&&session.valuesCorrect===5;state.mocks.push({score:session.score,values:session.valuesCorrect,pass,date:Date.now()});state.mocks=state.mocks.slice(-10);save();app.innerHTML=pageHead("MOCK EXAM RESULT",pass?"Pass standard met ✓":"Not yet","Pass requires at least 15/20 overall and 5/5 values.")+'<div class="cards"><div class="card"><h3>'+session.score+' / 20</h3><p>Overall score</p></div><div class="card"><h3>'+session.valuesCorrect+' / 5</h3><p>Values score</p></div></div><div class="actions"><button class="primary" data-view="home">Back to dashboard</button><button data-view="mock">Retake</button></div>';return}const p=Math.round(session.score/session.q.length*100);app.innerHTML=pageHead("SESSION COMPLETE",session.score+" / "+session.q.length,p+"% correct")+'<div class="actions"><button class="primary" data-view="practice">Train again</button><button data-view="mistakes">Review mistakes</button></div>'}
function recommended(){const r=nextAction();if(r.topic)start(r.topic);else route(r.view)}
function weakest(){const ids=Object.keys(topicInfo);ids.sort((a,b)=>pct(a)-pct(b));start(ids[0])}
function trainMistakes(){const ks=Object.keys(state.missed).filter(k=>state.missed[k]>0);const q=questions.filter(x=>ks.includes(x[1]));if(q.length)startSession(q,"mistakes");else practice()}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function route(view){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));({home:dashboard,syllabus,glossary,learn,readings,study,visual,map,cards,game,games,practice,mistakes,values,mock,readiness}[view]||dashboard)();window.scrollTo({top:0,behavior:"smooth"})}
document.addEventListener("click",e=>{const v=e.target.closest("[data-view]"),t=e.target.closest("[data-topic]"),a=e.target.closest("[data-answer]");if(v)return route(v.dataset.view);if(t)return start(t.dataset.topic);const l=e.target.closest("[data-lesson]");if(l)return lesson(l.dataset.lesson);if(a)return answer(+a.dataset.answer);const dom=e.target.closest("[data-domain]");if(dom)return openDomain(dom.dataset.domain);const dm=e.target.closest("[data-domain-master]");if(dm){state.domains[dm.dataset.domainMaster]=2;save();return openDomain(dm.dataset.domainMaster)}const stg=e.target.closest("[data-study]");if(stg)return openStudy(stg.dataset.study);const story=e.target.closest("[data-story]");if(story)return openStory(story.dataset.story);const sn=e.target.closest("[data-story-node]");if(sn)return storyNode(+sn.dataset.storyNode);if(e.target.closest("[data-story-check]"))return storyCheck();const sa=e.target.closest("[data-story-answer]");if(sa)return storyAnswer(+sa.dataset.storyAnswer);if(e.target.closest("[data-mapquiz]"))return mapQuiz();const ma=e.target.closest("[data-mapanswer]");if(ma)return mapAnswer(decodeURIComponent(ma.dataset.mapanswer));if(e.target.closest("[data-adaptive]"))return adaptiveReinforce();if(e.target.closest("[data-quest-start]"))return startQuest();const qb=e.target.closest("[data-quest-bin]");if(qb)return questAnswer(decodeURIComponent(qb.dataset.questBin));const sg=e.target.closest("[data-sortgame]");if(sg)return startSort(sg.dataset.sortgame);const bin=e.target.closest("[data-bin]");if(bin)return sortAnswer(decodeURIComponent(bin.dataset.bin));const kw=e.target.closest("[data-keyword]");if(kw)return gameAnswer(decodeURIComponent(kw.dataset.keyword));const p=e.target.closest("[data-place]"),r=e.target.closest("[data-reveal]");if(p)return showPlace(+p.dataset.place);if(r)return revealPlace(+r.dataset.reveal);if(e.target.closest("[data-flip]")){flipped=!flipped;return cards()}if(e.target.closest("[data-next]")){cardIndex=(cardIndex+1)%flashcards.length;flipped=false;return cards()}if(e.target.closest("[data-prev]")){cardIndex=(cardIndex-1+flashcards.length)%flashcards.length;flipped=false;return cards()}const rate=e.target.closest("[data-rate]");if(rate){const yes=rate.dataset.rate==="1";state.known[cardIndex]=yes;state.reviews[cardIndex]=Date.now()+(yes?3*86400000:10*60000);save();cardIndex=(cardIndex+1)%flashcards.length;flipped=false;return cards()}const act=e.target.closest("[data-action]");if(e.target.closest("#next-best"))return recommended();if(act?.dataset.action==="weak")return weakest();if(act?.dataset.action==="mistakes")return trainMistakes()});
route("home");