const modules=[
{id:"learn",icon:"▤",title:"Learn",desc:"Study the key topics from Our Common Bond",cls:"blue"},
{id:"visual",icon:"▥",title:"Infographics",desc:"Explore interactive visual guides",cls:"cyan"},
{id:"map",icon:"◇",title:"Map Lab",desc:"Learn states, territories and capitals",cls:"teal"},
{id:"cards",icon:"▣",title:"Flashcards",desc:"Build recall with spaced repetition",cls:"purple"},
{id:"practice",icon:"◎",title:"Reinforce",desc:"Targeted practice to strengthen knowledge",cls:"orange"},
{id:"mistakes",icon:"▧",title:"Mistakes",desc:"Review and master your weak areas",cls:"red"},
{id:"values",icon:"♟",title:"Values Lab",desc:"Practise Australian Values scenarios",cls:"green"},
{id:"mock",icon:"✓",title:"Mock Exam",desc:"Simulate the real test · 20 questions",cls:"gold"}
];
const topicInfo={
people:{name:"Australia & its people",icon:"🇦🇺",items:["Aboriginal and Torres Strait Islander peoples","States, territories and capitals","Australia Day: 26 January","Anzac Day: 25 April","Federation: 1 January 1901","Flags, anthem and national symbols"]},
rights:{name:"Democratic rights & liberties",icon:"🗳️",items:["Parliamentary democracy","Rule of law","Freedom of speech and expression","Freedom of religion and association","Equality of men and women","Responsibilities and privileges"]},
government:{name:"Government & the law",icon:"🏛️",items:["The Australian Constitution","Legislative, executive and judicial powers","Federal, state/territory and local government","House of Representatives and Senate","How a Bill becomes law","Courts, police and justice"]},
values:{name:"Australian Values",icon:"🤝",items:["Respect for freedom and dignity","Freedom within Australian law","Equality of opportunity","Peaceful democratic participation","A fair go and mutual respect","Community participation and loyalty"]}
};
const questions=[
["people","Australia became a federation in which year?",["1788","1851","1901","1915"],2,"Federation joined the six colonies into the Commonwealth on 1 January 1901."],
["people","What is Australia’s national capital?",["Sydney","Melbourne","Canberra","Adelaide"],2,"Canberra is the national capital."],
["people","Which colours are Australia’s national colours?",["Blue and white","Green and gold","Red and blue","Black and gold"],1,"Australia’s national colours are green and gold."],
["rights","Which is a responsibility of eligible Australian citizens aged 18 or over?",["Owning a home","Enrolling and voting","Joining a political party","Serving in the military"],1,"Eligible citizens aged 18 or over must enrol and vote."],
["rights","What does rule of law mean?",["Government is above the law","No person or group is above the law","Religious rules override law","Only citizens must obey law"],1,"Australian law applies to everyone."],
["rights","Which statement describes freedom of religion?",["Everyone must follow a religion","People may follow a religion or no religion","Only major religions are protected","Religious law replaces Australian law"],1,"People may practise a religion or choose no religion, within Australian law."],
["government","Which are the three powers of government?",["Federal, state, local","Legislative, executive, judicial","Parliament, police, council","King, Governor-General, Prime Minister"],1,"The three powers are legislative, executive and judicial."],
["government","A proposed new law introduced into Parliament is called what?",["A Bill","A ballot","A petition","A referendum"],0,"A proposed law is a Bill."],
["government","Who interprets and applies the law in cases?",["The media","The courts","Local councils","Political parties"],1,"Judicial power is exercised by courts."],
["values","If a religious practice conflicts with Australian law, which takes precedence?",["The religious rule","Family preference","Australian law","Whichever rule is older"],2,"Australian law applies to everyone."],
["values","Which best reflects equality in Australia?",["Leadership preference by gender","Equal opportunity regardless of gender","Only citizens receive legal protection","Ignore discrimination law"],1,"Equality includes equal opportunity regardless of gender."],
["values","A person strongly disagrees with a government decision. Which response reflects Australian values?",["Use violence","Peacefully protest within the law","Threaten officials","Stop others expressing views"],1,"Peaceful lawful protest is consistent with democratic values."],
["values","Which is consistent with peaceful democratic participation?",["Threatening opponents","Voting and lawful peaceful protest","Destroying property","Preventing others voting"],1,"Voting and peaceful lawful participation are democratic methods."],
["values","A colleague is treated unfairly because of gender. Which principle applies?",["Equality of opportunity","Compulsory association","Religious authority","Violence"],0,"Equality of opportunity applies regardless of gender."]
];
const flashcards=[
["When did Australia federate?","1 January 1901","people"],
["National capital?","Canberra","people"],
["Australia Day?","26 January","people"],
["Anzac Day?","25 April","people"],
["Three powers of government?","Legislative · Executive · Judicial","government"],
["Proposed law in Parliament?","A Bill","government"],
["Rule of law?","No person or group is above the law","rights"],
["Voting age for eligible citizens?","18 years and over","rights"],
["Can religion override Australian law?","No","values"],
["Values pass requirement?","All 5 values questions correct","values"],
["Overall pass requirement?","At least 15 out of 20","values"],
["Standard test time?","45 minutes","people"]
];
const places=[["South Australia","Adelaide"],["Victoria","Melbourne"],["Queensland","Brisbane"],["Western Australia","Perth"],["Tasmania","Hobart"],["New South Wales","Sydney"],["Northern Territory","Darwin"],["Australian Capital Territory","Canberra"]];
const app=document.querySelector("#app");
let state=loadState(),session=null,cardIndex=0,flipped=false;
function loadState(){try{const s=JSON.parse(localStorage.getItem("atest-state")||"{}");return {stats:s.stats||{},known:s.known||{},missed:s.missed||{},mocks:s.mocks||[]}}catch{return {stats:{},known:{},missed:{},mocks:[]}}}
function save(){localStorage.setItem("atest-state",JSON.stringify(state))}
function logo(sizeClass=""){return '<span class="'+sizeClass+' brand-logo"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="43" fill="none" stroke="currentColor" stroke-width="5"/><path d="M24 72h20V55c-9-4-14-12-14-22 0-16 12-27 28-27 18 0 31 13 31 31 0 9-4 18-11 24v11h-17V47" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M42 66V43M58 69V28M73 60V39" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><circle cx="42" cy="39" r="6" fill="currentColor"/><circle cx="58" cy="23" r="6" fill="currentColor"/><circle cx="73" cy="34" r="6" fill="currentColor"/><path d="M18 80h64" stroke="currentColor" stroke-width="6" stroke-linecap="round"/></svg></span>'}
function pct(id){const s=state.stats[id]||{c:0,t:0};return s.t?Math.round(s.c/s.t*100):0}
function dashboard(){
const ps={people:pct("people"),rights:pct("rights"),government:pct("government"),values:pct("values")};
app.innerHTML='<section class="hero"><div class="hero-main">'+logo("hero-logo")+'<div><h1><span>A-</span>TEST</h1><div class="tagline">LEARN · PRACTISE · BELONG</div><div class="promise">YOUR PATH TO AUSTRALIAN CITIZENSHIP</div></div></div><div class="hero-art"><div class="bridge"></div><div class="hero-quote">A Stronger<br>Australia<br>Together</div><div class="hero-meta">PEOPLE · RESPECT · OPPORTUNITY</div></div></section>'+
'<section class="pillars"><div class="pillar"><i>▤</i><div><b>Learn</b><small>Build knowledge</small></div></div><div class="pillar"><i>◉</i><div><b>Visualise</b><small>See the bigger picture</small></div></div><div class="pillar"><i>✺</i><div><b>Practise</b><small>Reinforce and improve</small></div></div><div class="pillar"><i>♕</i><div><b>Belong</b><small>Confident. Prepared. Australian.</small></div></div></section>'+
'<section class="feature-grid">'+modules.map(m=>'<button class="feature '+m.cls+'" data-view="'+m.id+'"><span class="icon">'+m.icon+'</span><span><h3>'+m.title+'</h3><p>'+m.desc+'</p></span><span class="go">›</span></button>').join("")+'</section>'+
'<section class="dashboard-lower"><div class="panel"><div class="panel-title">YOUR PROGRESS</div><div class="progress-grid">'+progress("people",ps.people,"#329dff")+progress("rights",ps.rights,"#31d7dc")+progress("government",ps.government,"#ffa550")+progress("values",ps.values,"#28e178")+'</div></div><div class="panel quick"><div class="panel-title">QUICK ACTIONS</div><button data-view="learn">▶ <span>Continue learning</span><b>›</b></button><button data-action="weak">⤨ <span>Train weakest area</span><b>›</b></button><button data-view="cards">▣ <span>Review flashcards</span><b>›</b></button><button data-view="mock">▥ <span>Take a mock exam</span><b>›</b></button></div><div class="panel quote"><div class="qmark">“</div><blockquote>Australia is strengthened by what we do: a fair go, a helping hand, and a better tomorrow together.</blockquote><small>A STRONGER AUSTRALIA TOGETHER</small></div></section>';
}
function progress(id,p,color){return '<div class="progress-item"><div class="ring" style="--p:'+p+';--ring:'+color+'"><strong>'+p+'%</strong></div><p>'+topicInfo[id].name+'</p></div>'}
function pageHead(kicker,title,lead){return '<div class="page-head"><div class="eyebrow">'+kicker+'</div><h2>'+title+'</h2><p class="lead">'+lead+'</p></div>'}
function learn(){app.innerHTML=pageHead("LEARNING HUB","Learn the four testable areas","Build understanding first, then lock it in with visualisation and retrieval.")+'<div class="cards">'+Object.entries(topicInfo).map(([id,t])=>'<article class="card"><h3>'+t.icon+' '+t.name+'</h3><ul>'+t.items.map(x=>'<li>'+x+'</li>').join("")+'</ul><div class="actions"><button class="primary" data-topic="'+id+'">Practise topic</button><button data-view="visual">Visualise</button></div></article>').join("")+'</div>'}
function visual(){app.innerHTML=pageHead("INFOGRAPHICS","See how the ideas connect","Use simple visual structures as memory anchors.")+'<div class="cards"><article class="card"><h3>🇦🇺 Australia timeline</h3><div class="flow"><span class="node">First peoples</span><span class="arrow">→</span><span class="node">1788</span><span class="arrow">→</span><span class="node">1851</span><span class="arrow">→</span><span class="node">1901 Federation</span></div><div class="visual">Anchor dates to events, not isolated numbers.</div></article><article class="card"><h3>🏛️ Government: two sets of three</h3><div class="flow"><span class="node">Legislative<br><small>makes laws</small></span><span class="node">Executive<br><small>puts them into action</small></span><span class="node">Judicial<br><small>interprets law</small></span></div><div class="visual">Powers ≠ levels of government.</div></article><article class="card"><h3>🗳️ Democratic beliefs</h3><div class="flow"><span class="node">Democracy</span><span class="arrow">+</span><span class="node">Rule of law</span><span class="arrow">+</span><span class="node">Freedom</span><span class="arrow">+</span><span class="node">Equality</span></div></article><article class="card"><h3>🤝 Values decision filter</h3><div class="flow"><span class="node">Lawful?</span><span class="arrow">→</span><span class="node">Peaceful?</span><span class="arrow">→</span><span class="node">Respectful & equal?</span></div><div class="visual">Values questions are a hard gate: 5 / 5.</div></article></div>'}
function map(){app.innerHTML=pageHead("MAP LAB","States, territories & capitals","Choose a jurisdiction, recall the capital, then reveal it.")+'<div class="maplab"><div class="card">'+places.map((p,i)=>'<button class="statebtn" data-place="'+i+'">'+p[0]+'</button>').join("")+'</div><div class="card" id="place"><h3>Choose a state or territory</h3><p class="hint">Say the capital aloud before revealing it.</p></div></div>'}
function showPlace(i){document.querySelectorAll(".statebtn").forEach((b,n)=>b.classList.toggle("active",n===i));const p=places[i];document.querySelector("#place").innerHTML='<h3>'+p[0]+'</h3><p class="hint">What is the capital?</p><button class="btn primary" data-reveal="'+i+'">Reveal</button>'}
function revealPlace(i){const p=places[i];document.querySelector("#place").innerHTML='<h3>'+p[0]+'</h3><div class="capital">'+p[1]+'</div><p>Lock the pair together: <b>'+p[0]+' → '+p[1]+'</b></p>'}
function cards(){const c=flashcards[cardIndex],known=!!state.known[cardIndex];app.innerHTML=pageHead("FLASHCARDS","Build recall","Think first, reveal second, then rate your recall.")+'<section class="card flash"><div class="eyebrow">'+c[2].toUpperCase()+' · '+(cardIndex+1)+' / '+flashcards.length+'</div><div class="face">'+(flipped?c[1]:c[0])+'</div><p class="hint">'+(flipped?"Answer":"Retrieve it before you tap reveal.")+'</p><div class="actions" style="justify-content:center"><button class="primary" data-flip>'+(flipped?"Show question":"Reveal answer")+'</button>'+(flipped?'<button data-rate="0">× Review again</button><button data-rate="1">✓ I know it</button>':"")+'</div><p class="'+(known?"good":"hint")+'">'+(known?"✓ Marked known":"Not mastered yet")+'</p></section><div class="actions" style="justify-content:center"><button data-prev>← Previous</button><button data-next>Next →</button></div>'}
function practice(){app.innerHTML=pageHead("REINFORCE","Targeted practice","Choose a topic or train everything together.")+'<div class="cards">'+Object.entries(topicInfo).map(([id,t])=>'<button class="card" data-topic="'+id+'" style="text-align:left;cursor:pointer"><h3>'+t.icon+' '+t.name+'</h3><p>Focused retrieval drill</p></button>').join("")+'</div><div class="actions"><button class="primary" data-topic="all">Mixed drill</button><button data-view="mistakes">Review mistakes</button></div>'}
function mistakes(){const ks=Object.keys(state.missed).filter(k=>state.missed[k]>0).sort((a,b)=>state.missed[b]-state.missed[a]);if(!ks.length){app.innerHTML=pageHead("MISTAKES","Clean slate ✓","No unresolved mistakes yet. Keep practising to generate useful signals.")+'<button class="btn primary" data-view="practice">Start practice</button>';return}app.innerHTML=pageHead("MISTAKES","Turn errors into assets","The questions below are currently your highest-value review opportunities.")+'<div class="cards">'+ks.map(k=>'<article class="card"><div class="eyebrow">'+state.missed[k]+' MISS'+(state.missed[k]>1?"ES":"")+'</div><h3>'+k+'</h3></article>').join("")+'</div><div class="actions"><button class="primary" data-action="mistakes">Train my mistakes</button></div>'}
function values(){start("values")}
function mock(){const valuesQ=questions.filter(q=>q[0]==="values");const other=questions.filter(q=>q[0]!=="values");const picked=[];for(let i=0;i<15;i++)picked.push(other[i%other.length]);for(let i=0;i<5;i++)picked.push(valuesQ[i%valuesQ.length]);startSession(shuffle(picked),"mock")}
function start(mode){let q=mode==="all"?questions.slice():questions.filter(x=>x[0]===mode);startSession(shuffle(q),mode)}
function startSession(q,mode){session={q,i:0,score:0,mode,valuesCorrect:0};drawQuestion()}
function drawQuestion(){const q=session.q[session.i];app.innerHTML='<section class="card quiz"><div class="eyebrow">'+(session.mode==="mock"?"MOCK EXAM":"REINFORCEMENT")+' · '+(session.i+1)+' / '+session.q.length+'</div><div class="question">'+q[1]+'</div><div class="choices">'+q[2].map((x,i)=>'<button class="choice" data-answer="'+i+'">'+String.fromCharCode(65+i)+'. '+x+'</button>').join("")+'</div><div id="feedback"></div></section>'}
function answer(i){const q=session.q[session.i],ok=i===q[3];if(ok){session.score++;if(q[0]==="values")session.valuesCorrect++;state.missed[q[1]]=0}else state.missed[q[1]]=(state.missed[q[1]]||0)+1;const s=state.stats[q[0]]||{c:0,t:0};s.t++;if(ok)s.c++;state.stats[q[0]]=s;save();document.querySelectorAll(".choice").forEach((b,n)=>{b.disabled=true;if(n===q[3])b.classList.add("correct");else if(n===i)b.classList.add("wrong")});document.querySelector("#feedback").innerHTML='<div class="feedback"><b class="'+(ok?"good":"bad")+'">'+(ok?"✓ Correct":"✕ Not yet")+'</b><p>'+q[4]+'</p><button class="btn primary" id="next">'+(session.i===session.q.length-1?"Finish":"Next")+'</button></div>';document.querySelector("#next").onclick=()=>{session.i++;session.i>=session.q.length?finish():drawQuestion()}}
function finish(){if(session.mode==="mock"){const pass=session.score>=15&&session.valuesCorrect===5;state.mocks.push({score:session.score,values:session.valuesCorrect,pass,date:Date.now()});state.mocks=state.mocks.slice(-10);save();app.innerHTML=pageHead("MOCK EXAM RESULT",pass?"Pass standard met ✓":"Not yet","Pass requires at least 15/20 overall and 5/5 values.")+'<div class="cards"><div class="card"><h3>'+session.score+' / 20</h3><p>Overall score</p></div><div class="card"><h3>'+session.valuesCorrect+' / 5</h3><p>Values score</p></div></div><div class="actions"><button class="primary" data-view="home">Back to dashboard</button><button data-view="mock">Retake</button></div>';return}const p=Math.round(session.score/session.q.length*100);app.innerHTML=pageHead("SESSION COMPLETE",session.score+" / "+session.q.length,p+"% correct")+'<div class="actions"><button class="primary" data-view="practice">Train again</button><button data-view="mistakes">Review mistakes</button></div>'}
function weakest(){const ids=Object.keys(topicInfo);ids.sort((a,b)=>pct(a)-pct(b));start(ids[0])}
function trainMistakes(){const ks=Object.keys(state.missed).filter(k=>state.missed[k]>0);const q=questions.filter(x=>ks.includes(x[1]));if(q.length)startSession(q,"mistakes");else practice()}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function route(view){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));({home:dashboard,learn,visual,map,cards,practice,mistakes,values,mock}[view]||dashboard)();window.scrollTo({top:0,behavior:"smooth"})}
document.addEventListener("click",e=>{const v=e.target.closest("[data-view]"),t=e.target.closest("[data-topic]"),a=e.target.closest("[data-answer]");if(v)return route(v.dataset.view);if(t)return start(t.dataset.topic);if(a)return answer(+a.dataset.answer);const p=e.target.closest("[data-place]"),r=e.target.closest("[data-reveal]");if(p)return showPlace(+p.dataset.place);if(r)return revealPlace(+r.dataset.reveal);if(e.target.closest("[data-flip]")){flipped=!flipped;return cards()}if(e.target.closest("[data-next]")){cardIndex=(cardIndex+1)%flashcards.length;flipped=false;return cards()}if(e.target.closest("[data-prev]")){cardIndex=(cardIndex-1+flashcards.length)%flashcards.length;flipped=false;return cards()}const rate=e.target.closest("[data-rate]");if(rate){state.known[cardIndex]=rate.dataset.rate==="1";save();cardIndex=(cardIndex+1)%flashcards.length;flipped=false;return cards()}const act=e.target.closest("[data-action]");if(act?.dataset.action==="weak")return weakest();if(act?.dataset.action==="mistakes")return trainMistakes()});
route("home");