window.ATEST_BANK=[
["people","Who are the first inhabitants of Australia?",["Aboriginal and Torres Strait Islander peoples","British settlers","European explorers","Pacific Islanders"],0,"First peoples → Aboriginal + Torres Strait Islander peoples"],
["people","On which date did the First Fleet arrive from Great Britain?",["25 April 1915","26 January 1788","1 January 1901","3 March 1986"],1,"First Fleet → 26 January 1788"],
["people","When did Australia become a federation?",["1788","1851","1901","1915"],2,"Six colonies → one Commonwealth → 1901"],
["people","What is Australia's national capital?",["Sydney","Melbourne","Canberra","Adelaide"],2,"Australia → Canberra"],
["people","What is the capital of South Australia?",["Perth","Adelaide","Hobart","Darwin"],1,"South Australia → Adelaide"],
["people","What is the capital of Victoria?",["Melbourne","Sydney","Brisbane","Canberra"],0,"Victoria → Melbourne"],
["people","What is the capital of Queensland?",["Darwin","Brisbane","Perth","Hobart"],1,"Queensland → Brisbane"],
["people","What is the capital of Western Australia?",["Adelaide","Perth","Melbourne","Darwin"],1,"Western Australia → Perth"],
["people","What is the capital of Tasmania?",["Hobart","Canberra","Darwin","Sydney"],0,"Tasmania → Hobart"],
["people","What is commemorated on Anzac Day?",["Federation","The landing of the ANZACs at Gallipoli during the First World War","The First Fleet","Opening of Parliament House"],1,"ANZAC → Gallipoli → 25 April"],
["people","What is Australia's national floral emblem?",["Waratah","Golden wattle","Rose","Eucalyptus"],1,"National floral emblem → golden wattle"],
["people","What are Australia's national colours?",["Blue and white","Red and black","Green and gold","Green and white"],2,"Australia → green + gold"],
["rights","Which is a responsibility of Australian citizens aged 18 or over?",["Own a home","Enrol and vote in elections and referendums","Join a political party","Serve full-time in the military"],1,"Citizen 18+ → enrol → vote"],
["rights","What does freedom of speech mean in Australia?",["You may say anything without legal limits","People may express ideas freely within the law","Only citizens may criticise government","Speech needs government approval"],1,"Speech → free within Australian law"],
["rights","Can Australians choose not to follow a religion?",["Yes","No","Only with permission","Only after age 21"],0,"Freedom of religion → religion or no religion"],
["rights","What does a 'fair go' refer to?",["Everyone receiving identical outcomes","Fair opportunity based on effort and talent","Citizens never paying tax","Government choosing careers"],1,"Fair go → fair opportunity"],
["rights","Which is a privilege of Australian citizenship?",["Ignoring laws","Applying for an Australian passport","Refusing jury service when called","Voting twice"],1,"Citizenship privilege → Australian passport"],
["rights","When called and eligible, what civic service may a citizen need to perform?",["Jury service","Military service every year","Council employment","Police training"],0,"Called + eligible → jury service"],
["rights","What is expected of everyone in Australia?",["Obey Australian laws","Join the same religion","Vote for the government","Speak only English at home"],0,"Everyone → obey Australian law"],
["government","What document sets out the basic rules for the government of Australia?",["The Australian Constitution","The Magna Carta","The Electoral Roll","The national anthem"],0,"Basic rules → Constitution"],
["government","What are the three powers of government?",["Federal, state, local","Legislative, executive, judicial","Parliament, police, council","King, Governor-General, Prime Minister"],1,"MAKE → DO → JUDGE"],
["government","Which level of government is primarily responsible for immigration?",["Local","State","Federal","Council"],2,"Immigration → federal"],
["government","Which level commonly manages rubbish collection and local parks?",["Federal","Local council","High Court","Senate"],1,"Local streets + parks + rubbish → council"],
["government","A proposed new law introduced into Parliament is called what?",["A Bill","A ballot","A petition","A referendum"],0,"Bill → Parliament → law"],
["government","What are the two Houses of the Australian Parliament?",["Senate and House of Representatives","Cabinet and High Court","House of Lords and Commons","Federal and State Houses"],0,"Parliament → House + Senate"],
["government","Who represents the King in Australia at the federal level?",["Prime Minister","Governor-General","Chief Justice","Premier"],1,"King → Governor-General"],
["government","What is a referendum used for?",["Choosing a mayor","Changing the Australian Constitution","Selecting judges","Setting tax rates"],1,"Constitutional change → referendum"],
["government","Are Australian courts independent of Parliament and government?",["Yes","No","Only federal courts","Only during elections"],0,"Courts → independent"],
["values","A person strongly disagrees with a government decision. Which response reflects Australian values?",["Use violence","Peacefully protest within the law","Threaten officials","Stop others speaking"],1,"Disagree → peaceful action → law"],
["values","If a religious practice conflicts with Australian law, which takes precedence?",["Religious rule","Family preference","Australian law","Whichever is older"],2,"Everyone → Australian law"],
["values","Which statement best reflects equality in Australia?",["Men should receive preference","People should have equal opportunity regardless of gender","Only citizens deserve legal protection","Employers may ignore discrimination law"],1,"Equal dignity → equal opportunity"],
["values","What does freedom of association mean?",["Everyone must join a group","People may join or leave lawful groups voluntarily","Employers choose your groups","Government chooses your religion"],1,"Association = choice"],
["values","When people hold different lawful beliefs, what is expected?",["Respect lawful differences","Silence minority views","Use force","Ignore Australian law"],0,"Different beliefs → respect + law"],
["values","Is violence against another person acceptable when there is disagreement?",["Yes, if angry","Yes, in private","No","Only between family members"],2,"Disagreement ≠ violence"],
["values","Which principle applies to men and women in Australia?",["Men have more rights","Women have more rights","Equal rights and opportunities","Different laws apply"],2,"Women + men → equal rights"],
["values","Which action best shows mutual respect?",["Insulting someone for their beliefs","Listening to different lawful views without violence","Forcing your view on others","Excluding people by race"],1,"Respect → lawful difference without violence"],
["values","Should people obey Australian laws even when they personally disagree?",["Yes","No","Only citizens","Only during elections"],0,"Rule of law → applies to everyone"],
["values","Which is consistent with Australian values?",["Racial discrimination","Equality of opportunity","Political violence","Forced religion"],1,"Australian values → equality of opportunity"],
["values","Can a person peacefully criticise the government?",["Yes, within the law","No","Only politicians can","Only during elections"],0,"Democracy → peaceful criticism within law"],
["values","What should happen when Australians want political change?",["Use peaceful democratic processes","Use threats","Ignore elections","Use violence"],0,"Change → peaceful democracy"]
];